package com.sc.dmh.mapper;

import com.sc.dmh.beans.TabRpf;
import com.sc.dmh.beans.TabRpfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabRpfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int countByExample(TabRpfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int deleteByExample(TabRpfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rpfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int insert(TabRpf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int insertSelective(TabRpf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    List<TabRpf> selectByExample(TabRpfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    TabRpf selectByPrimaryKey(Integer rpfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabRpf record, @Param("example") TabRpfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabRpf record, @Param("example") TabRpfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabRpf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabRpf record);
}