package com.sc.dmh.mapper;

import com.sc.dmh.beans.ViewCbfp;
import com.sc.dmh.beans.ViewCbfpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewCbfpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int countByExample(ViewCbfpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int deleteByExample(ViewCbfpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int insert(ViewCbfp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int insertSelective(ViewCbfp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    List<ViewCbfp> selectByExample(ViewCbfpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ViewCbfp record, @Param("example") ViewCbfpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ViewCbfp record, @Param("example") ViewCbfpExample example);
}