package com.sc.dmh.beans;

import java.io.Serializable;

public class TabCz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_id
     *
     * @mbggenerated
     */
    private Integer czId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_name
     *
     * @mbggenerated
     */
    private String czName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_typeId
     *
     * @mbggenerated
     */
    private Integer czTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_order
     *
     * @mbggenerated
     */
    private Integer czOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_bak1
     *
     * @mbggenerated
     */
    private String czBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_bak2
     *
     * @mbggenerated
     */
    private String czBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cz.cz_bak3
     *
     * @mbggenerated
     */
    private String czBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_cz
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_id
     *
     * @return the value of tab_cz.cz_id
     *
     * @mbggenerated
     */
    public Integer getCzId() {
        return czId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_id
     *
     * @param czId the value for tab_cz.cz_id
     *
     * @mbggenerated
     */
    public void setCzId(Integer czId) {
        this.czId = czId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_name
     *
     * @return the value of tab_cz.cz_name
     *
     * @mbggenerated
     */
    public String getCzName() {
        return czName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_name
     *
     * @param czName the value for tab_cz.cz_name
     *
     * @mbggenerated
     */
    public void setCzName(String czName) {
        this.czName = czName == null ? null : czName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_typeId
     *
     * @return the value of tab_cz.cz_typeId
     *
     * @mbggenerated
     */
    public Integer getCzTypeid() {
        return czTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_typeId
     *
     * @param czTypeid the value for tab_cz.cz_typeId
     *
     * @mbggenerated
     */
    public void setCzTypeid(Integer czTypeid) {
        this.czTypeid = czTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_order
     *
     * @return the value of tab_cz.cz_order
     *
     * @mbggenerated
     */
    public Integer getCzOrder() {
        return czOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_order
     *
     * @param czOrder the value for tab_cz.cz_order
     *
     * @mbggenerated
     */
    public void setCzOrder(Integer czOrder) {
        this.czOrder = czOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_bak1
     *
     * @return the value of tab_cz.cz_bak1
     *
     * @mbggenerated
     */
    public String getCzBak1() {
        return czBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_bak1
     *
     * @param czBak1 the value for tab_cz.cz_bak1
     *
     * @mbggenerated
     */
    public void setCzBak1(String czBak1) {
        this.czBak1 = czBak1 == null ? null : czBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_bak2
     *
     * @return the value of tab_cz.cz_bak2
     *
     * @mbggenerated
     */
    public String getCzBak2() {
        return czBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_bak2
     *
     * @param czBak2 the value for tab_cz.cz_bak2
     *
     * @mbggenerated
     */
    public void setCzBak2(String czBak2) {
        this.czBak2 = czBak2 == null ? null : czBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cz.cz_bak3
     *
     * @return the value of tab_cz.cz_bak3
     *
     * @mbggenerated
     */
    public String getCzBak3() {
        return czBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cz.cz_bak3
     *
     * @param czBak3 the value for tab_cz.cz_bak3
     *
     * @mbggenerated
     */
    public void setCzBak3(String czBak3) {
        this.czBak3 = czBak3 == null ? null : czBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cz
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabCz other = (TabCz) that;
        return (this.getCzId() == null ? other.getCzId() == null : this.getCzId().equals(other.getCzId()))
            && (this.getCzName() == null ? other.getCzName() == null : this.getCzName().equals(other.getCzName()))
            && (this.getCzTypeid() == null ? other.getCzTypeid() == null : this.getCzTypeid().equals(other.getCzTypeid()))
            && (this.getCzOrder() == null ? other.getCzOrder() == null : this.getCzOrder().equals(other.getCzOrder()))
            && (this.getCzBak1() == null ? other.getCzBak1() == null : this.getCzBak1().equals(other.getCzBak1()))
            && (this.getCzBak2() == null ? other.getCzBak2() == null : this.getCzBak2().equals(other.getCzBak2()))
            && (this.getCzBak3() == null ? other.getCzBak3() == null : this.getCzBak3().equals(other.getCzBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cz
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCzId() == null) ? 0 : getCzId().hashCode());
        result = prime * result + ((getCzName() == null) ? 0 : getCzName().hashCode());
        result = prime * result + ((getCzTypeid() == null) ? 0 : getCzTypeid().hashCode());
        result = prime * result + ((getCzOrder() == null) ? 0 : getCzOrder().hashCode());
        result = prime * result + ((getCzBak1() == null) ? 0 : getCzBak1().hashCode());
        result = prime * result + ((getCzBak2() == null) ? 0 : getCzBak2().hashCode());
        result = prime * result + ((getCzBak3() == null) ? 0 : getCzBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cz
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", czId=").append(czId);
        sb.append(", czName=").append(czName);
        sb.append(", czTypeid=").append(czTypeid);
        sb.append(", czOrder=").append(czOrder);
        sb.append(", czBak1=").append(czBak1);
        sb.append(", czBak2=").append(czBak2);
        sb.append(", czBak3=").append(czBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}