package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TabCbfp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    private Integer cbfpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.kemu_id
     *
     * @mbggenerated
     */
    private Integer kemuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    private BigDecimal kemuSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.dep_id
     *
     * @mbggenerated
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    private Date cbfpDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    private String cbfpBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    private String cbfpBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    private String cbfpBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_cbfp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.cbfp_id
     *
     * @return the value of tab_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    public Integer getCbfpId() {
        return cbfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.cbfp_id
     *
     * @param cbfpId the value for tab_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    public void setCbfpId(Integer cbfpId) {
        this.cbfpId = cbfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.kemu_id
     *
     * @return the value of tab_cbfp.kemu_id
     *
     * @mbggenerated
     */
    public Integer getKemuId() {
        return kemuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.kemu_id
     *
     * @param kemuId the value for tab_cbfp.kemu_id
     *
     * @mbggenerated
     */
    public void setKemuId(Integer kemuId) {
        this.kemuId = kemuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.user_id
     *
     * @return the value of tab_cbfp.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.user_id
     *
     * @param userId the value for tab_cbfp.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.kemu_sum
     *
     * @return the value of tab_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    public BigDecimal getKemuSum() {
        return kemuSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.kemu_sum
     *
     * @param kemuSum the value for tab_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    public void setKemuSum(BigDecimal kemuSum) {
        this.kemuSum = kemuSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.dep_id
     *
     * @return the value of tab_cbfp.dep_id
     *
     * @mbggenerated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.dep_id
     *
     * @param depId the value for tab_cbfp.dep_id
     *
     * @mbggenerated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.cbfp_date
     *
     * @return the value of tab_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    public Date getCbfpDate() {
        return cbfpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.cbfp_date
     *
     * @param cbfpDate the value for tab_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    public void setCbfpDate(Date cbfpDate) {
        this.cbfpDate = cbfpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.cbfp_bak1
     *
     * @return the value of tab_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    public String getCbfpBak1() {
        return cbfpBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.cbfp_bak1
     *
     * @param cbfpBak1 the value for tab_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    public void setCbfpBak1(String cbfpBak1) {
        this.cbfpBak1 = cbfpBak1 == null ? null : cbfpBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.cbfp_bak2
     *
     * @return the value of tab_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    public String getCbfpBak2() {
        return cbfpBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.cbfp_bak2
     *
     * @param cbfpBak2 the value for tab_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    public void setCbfpBak2(String cbfpBak2) {
        this.cbfpBak2 = cbfpBak2 == null ? null : cbfpBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_cbfp.cbfp_bak3
     *
     * @return the value of tab_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    public String getCbfpBak3() {
        return cbfpBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_cbfp.cbfp_bak3
     *
     * @param cbfpBak3 the value for tab_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    public void setCbfpBak3(String cbfpBak3) {
        this.cbfpBak3 = cbfpBak3 == null ? null : cbfpBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cbfp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabCbfp other = (TabCbfp) that;
        return (this.getCbfpId() == null ? other.getCbfpId() == null : this.getCbfpId().equals(other.getCbfpId()))
            && (this.getKemuId() == null ? other.getKemuId() == null : this.getKemuId().equals(other.getKemuId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getKemuSum() == null ? other.getKemuSum() == null : this.getKemuSum().equals(other.getKemuSum()))
            && (this.getDepId() == null ? other.getDepId() == null : this.getDepId().equals(other.getDepId()))
            && (this.getCbfpDate() == null ? other.getCbfpDate() == null : this.getCbfpDate().equals(other.getCbfpDate()))
            && (this.getCbfpBak1() == null ? other.getCbfpBak1() == null : this.getCbfpBak1().equals(other.getCbfpBak1()))
            && (this.getCbfpBak2() == null ? other.getCbfpBak2() == null : this.getCbfpBak2().equals(other.getCbfpBak2()))
            && (this.getCbfpBak3() == null ? other.getCbfpBak3() == null : this.getCbfpBak3().equals(other.getCbfpBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cbfp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCbfpId() == null) ? 0 : getCbfpId().hashCode());
        result = prime * result + ((getKemuId() == null) ? 0 : getKemuId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getKemuSum() == null) ? 0 : getKemuSum().hashCode());
        result = prime * result + ((getDepId() == null) ? 0 : getDepId().hashCode());
        result = prime * result + ((getCbfpDate() == null) ? 0 : getCbfpDate().hashCode());
        result = prime * result + ((getCbfpBak1() == null) ? 0 : getCbfpBak1().hashCode());
        result = prime * result + ((getCbfpBak2() == null) ? 0 : getCbfpBak2().hashCode());
        result = prime * result + ((getCbfpBak3() == null) ? 0 : getCbfpBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_cbfp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cbfpId=").append(cbfpId);
        sb.append(", kemuId=").append(kemuId);
        sb.append(", userId=").append(userId);
        sb.append(", kemuSum=").append(kemuSum);
        sb.append(", depId=").append(depId);
        sb.append(", cbfpDate=").append(cbfpDate);
        sb.append(", cbfpBak1=").append(cbfpBak1);
        sb.append(", cbfpBak2=").append(cbfpBak2);
        sb.append(", cbfpBak3=").append(cbfpBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}