package com.sc.dmh.beans;

import java.io.Serializable;

public class TabDepartment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_id
     *
     * @mbggenerated
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_name
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_order
     *
     * @mbggenerated
     */
    private Integer departmentOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_bak1
     *
     * @mbggenerated
     */
    private String departmentBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_bak2
     *
     * @mbggenerated
     */
    private String departmentBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_department.department_bak3
     *
     * @mbggenerated
     */
    private String departmentBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_id
     *
     * @return the value of tab_department.department_id
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_id
     *
     * @param departmentId the value for tab_department.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_name
     *
     * @return the value of tab_department.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_name
     *
     * @param departmentName the value for tab_department.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_order
     *
     * @return the value of tab_department.department_order
     *
     * @mbggenerated
     */
    public Integer getDepartmentOrder() {
        return departmentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_order
     *
     * @param departmentOrder the value for tab_department.department_order
     *
     * @mbggenerated
     */
    public void setDepartmentOrder(Integer departmentOrder) {
        this.departmentOrder = departmentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_bak1
     *
     * @return the value of tab_department.department_bak1
     *
     * @mbggenerated
     */
    public String getDepartmentBak1() {
        return departmentBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_bak1
     *
     * @param departmentBak1 the value for tab_department.department_bak1
     *
     * @mbggenerated
     */
    public void setDepartmentBak1(String departmentBak1) {
        this.departmentBak1 = departmentBak1 == null ? null : departmentBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_bak2
     *
     * @return the value of tab_department.department_bak2
     *
     * @mbggenerated
     */
    public String getDepartmentBak2() {
        return departmentBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_bak2
     *
     * @param departmentBak2 the value for tab_department.department_bak2
     *
     * @mbggenerated
     */
    public void setDepartmentBak2(String departmentBak2) {
        this.departmentBak2 = departmentBak2 == null ? null : departmentBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_department.department_bak3
     *
     * @return the value of tab_department.department_bak3
     *
     * @mbggenerated
     */
    public String getDepartmentBak3() {
        return departmentBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_department.department_bak3
     *
     * @param departmentBak3 the value for tab_department.department_bak3
     *
     * @mbggenerated
     */
    public void setDepartmentBak3(String departmentBak3) {
        this.departmentBak3 = departmentBak3 == null ? null : departmentBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabDepartment other = (TabDepartment) that;
        return (this.getDepartmentId() == null ? other.getDepartmentId() == null : this.getDepartmentId().equals(other.getDepartmentId()))
            && (this.getDepartmentName() == null ? other.getDepartmentName() == null : this.getDepartmentName().equals(other.getDepartmentName()))
            && (this.getDepartmentOrder() == null ? other.getDepartmentOrder() == null : this.getDepartmentOrder().equals(other.getDepartmentOrder()))
            && (this.getDepartmentBak1() == null ? other.getDepartmentBak1() == null : this.getDepartmentBak1().equals(other.getDepartmentBak1()))
            && (this.getDepartmentBak2() == null ? other.getDepartmentBak2() == null : this.getDepartmentBak2().equals(other.getDepartmentBak2()))
            && (this.getDepartmentBak3() == null ? other.getDepartmentBak3() == null : this.getDepartmentBak3().equals(other.getDepartmentBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDepartmentId() == null) ? 0 : getDepartmentId().hashCode());
        result = prime * result + ((getDepartmentName() == null) ? 0 : getDepartmentName().hashCode());
        result = prime * result + ((getDepartmentOrder() == null) ? 0 : getDepartmentOrder().hashCode());
        result = prime * result + ((getDepartmentBak1() == null) ? 0 : getDepartmentBak1().hashCode());
        result = prime * result + ((getDepartmentBak2() == null) ? 0 : getDepartmentBak2().hashCode());
        result = prime * result + ((getDepartmentBak3() == null) ? 0 : getDepartmentBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", departmentId=").append(departmentId);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", departmentOrder=").append(departmentOrder);
        sb.append(", departmentBak1=").append(departmentBak1);
        sb.append(", departmentBak2=").append(departmentBak2);
        sb.append(", departmentBak3=").append(departmentBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}