package com.sc.dmh.beans;

import java.util.ArrayList;
import java.util.List;

public class TabDepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public TabDepartmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Integer value) {
            addCriterion("department_id =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Integer value) {
            addCriterion("department_id <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Integer value) {
            addCriterion("department_id >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_id >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Integer value) {
            addCriterion("department_id <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("department_id <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Integer> values) {
            addCriterion("department_id in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Integer> values) {
            addCriterion("department_id not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("department_id between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("department_id not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNull() {
            addCriterion("department_name is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNotNull() {
            addCriterion("department_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameEqualTo(String value) {
            addCriterion("department_name =", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotEqualTo(String value) {
            addCriterion("department_name <>", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThan(String value) {
            addCriterion("department_name >", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("department_name >=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThan(String value) {
            addCriterion("department_name <", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("department_name <=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLike(String value) {
            addCriterion("department_name like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotLike(String value) {
            addCriterion("department_name not like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIn(List<String> values) {
            addCriterion("department_name in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotIn(List<String> values) {
            addCriterion("department_name not in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameBetween(String value1, String value2) {
            addCriterion("department_name between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotBetween(String value1, String value2) {
            addCriterion("department_name not between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIsNull() {
            addCriterion("department_order is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIsNotNull() {
            addCriterion("department_order is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderEqualTo(Integer value) {
            addCriterion("department_order =", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotEqualTo(Integer value) {
            addCriterion("department_order <>", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderGreaterThan(Integer value) {
            addCriterion("department_order >", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_order >=", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderLessThan(Integer value) {
            addCriterion("department_order <", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderLessThanOrEqualTo(Integer value) {
            addCriterion("department_order <=", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIn(List<Integer> values) {
            addCriterion("department_order in", values, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotIn(List<Integer> values) {
            addCriterion("department_order not in", values, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderBetween(Integer value1, Integer value2) {
            addCriterion("department_order between", value1, value2, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("department_order not between", value1, value2, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1IsNull() {
            addCriterion("department_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1IsNotNull() {
            addCriterion("department_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1EqualTo(String value) {
            addCriterion("department_bak1 =", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1NotEqualTo(String value) {
            addCriterion("department_bak1 <>", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1GreaterThan(String value) {
            addCriterion("department_bak1 >", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1GreaterThanOrEqualTo(String value) {
            addCriterion("department_bak1 >=", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1LessThan(String value) {
            addCriterion("department_bak1 <", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1LessThanOrEqualTo(String value) {
            addCriterion("department_bak1 <=", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1Like(String value) {
            addCriterion("department_bak1 like", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1NotLike(String value) {
            addCriterion("department_bak1 not like", value, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1In(List<String> values) {
            addCriterion("department_bak1 in", values, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1NotIn(List<String> values) {
            addCriterion("department_bak1 not in", values, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1Between(String value1, String value2) {
            addCriterion("department_bak1 between", value1, value2, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak1NotBetween(String value1, String value2) {
            addCriterion("department_bak1 not between", value1, value2, "departmentBak1");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2IsNull() {
            addCriterion("department_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2IsNotNull() {
            addCriterion("department_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2EqualTo(String value) {
            addCriterion("department_bak2 =", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2NotEqualTo(String value) {
            addCriterion("department_bak2 <>", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2GreaterThan(String value) {
            addCriterion("department_bak2 >", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2GreaterThanOrEqualTo(String value) {
            addCriterion("department_bak2 >=", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2LessThan(String value) {
            addCriterion("department_bak2 <", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2LessThanOrEqualTo(String value) {
            addCriterion("department_bak2 <=", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2Like(String value) {
            addCriterion("department_bak2 like", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2NotLike(String value) {
            addCriterion("department_bak2 not like", value, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2In(List<String> values) {
            addCriterion("department_bak2 in", values, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2NotIn(List<String> values) {
            addCriterion("department_bak2 not in", values, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2Between(String value1, String value2) {
            addCriterion("department_bak2 between", value1, value2, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak2NotBetween(String value1, String value2) {
            addCriterion("department_bak2 not between", value1, value2, "departmentBak2");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3IsNull() {
            addCriterion("department_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3IsNotNull() {
            addCriterion("department_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3EqualTo(String value) {
            addCriterion("department_bak3 =", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3NotEqualTo(String value) {
            addCriterion("department_bak3 <>", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3GreaterThan(String value) {
            addCriterion("department_bak3 >", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3GreaterThanOrEqualTo(String value) {
            addCriterion("department_bak3 >=", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3LessThan(String value) {
            addCriterion("department_bak3 <", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3LessThanOrEqualTo(String value) {
            addCriterion("department_bak3 <=", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3Like(String value) {
            addCriterion("department_bak3 like", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3NotLike(String value) {
            addCriterion("department_bak3 not like", value, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3In(List<String> values) {
            addCriterion("department_bak3 in", values, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3NotIn(List<String> values) {
            addCriterion("department_bak3 not in", values, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3Between(String value1, String value2) {
            addCriterion("department_bak3 between", value1, value2, "departmentBak3");
            return (Criteria) this;
        }

        public Criteria andDepartmentBak3NotBetween(String value1, String value2) {
            addCriterion("department_bak3 not between", value1, value2, "departmentBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_department
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_department
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}