package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TabHsfJiecun implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_id
     *
     * @mbggenerated
     */
    private Integer jiecunId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_rs
     *
     * @mbggenerated
     */
    private Integer jiecunRs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_money
     *
     * @mbggenerated
     */
    private BigDecimal jiecunMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_month
     *
     * @mbggenerated
     */
    private Date jiecunMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_autotime
     *
     * @mbggenerated
     */
    private Date jiecunAutotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.dep_id
     *
     * @mbggenerated
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_state
     *
     * @mbggenerated
     */
    private Integer jiecunState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_number
     *
     * @mbggenerated
     */
    private Integer jiecunNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_bak1
     *
     * @mbggenerated
     */
    private String jiecunBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_bak2
     *
     * @mbggenerated
     */
    private String jiecunBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_jiecun.jiecun_bak3
     *
     * @mbggenerated
     */
    private String jiecunBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_id
     *
     * @return the value of tab_hsf_jiecun.jiecun_id
     *
     * @mbggenerated
     */
    public Integer getJiecunId() {
        return jiecunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_id
     *
     * @param jiecunId the value for tab_hsf_jiecun.jiecun_id
     *
     * @mbggenerated
     */
    public void setJiecunId(Integer jiecunId) {
        this.jiecunId = jiecunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_rs
     *
     * @return the value of tab_hsf_jiecun.jiecun_rs
     *
     * @mbggenerated
     */
    public Integer getJiecunRs() {
        return jiecunRs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_rs
     *
     * @param jiecunRs the value for tab_hsf_jiecun.jiecun_rs
     *
     * @mbggenerated
     */
    public void setJiecunRs(Integer jiecunRs) {
        this.jiecunRs = jiecunRs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_money
     *
     * @return the value of tab_hsf_jiecun.jiecun_money
     *
     * @mbggenerated
     */
    public BigDecimal getJiecunMoney() {
        return jiecunMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_money
     *
     * @param jiecunMoney the value for tab_hsf_jiecun.jiecun_money
     *
     * @mbggenerated
     */
    public void setJiecunMoney(BigDecimal jiecunMoney) {
        this.jiecunMoney = jiecunMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_month
     *
     * @return the value of tab_hsf_jiecun.jiecun_month
     *
     * @mbggenerated
     */
    public Date getJiecunMonth() {
        return jiecunMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_month
     *
     * @param jiecunMonth the value for tab_hsf_jiecun.jiecun_month
     *
     * @mbggenerated
     */
    public void setJiecunMonth(Date jiecunMonth) {
        this.jiecunMonth = jiecunMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_autotime
     *
     * @return the value of tab_hsf_jiecun.jiecun_autotime
     *
     * @mbggenerated
     */
    public Date getJiecunAutotime() {
        return jiecunAutotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_autotime
     *
     * @param jiecunAutotime the value for tab_hsf_jiecun.jiecun_autotime
     *
     * @mbggenerated
     */
    public void setJiecunAutotime(Date jiecunAutotime) {
        this.jiecunAutotime = jiecunAutotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.user_id
     *
     * @return the value of tab_hsf_jiecun.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.user_id
     *
     * @param userId the value for tab_hsf_jiecun.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.dep_id
     *
     * @return the value of tab_hsf_jiecun.dep_id
     *
     * @mbggenerated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.dep_id
     *
     * @param depId the value for tab_hsf_jiecun.dep_id
     *
     * @mbggenerated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_state
     *
     * @return the value of tab_hsf_jiecun.jiecun_state
     *
     * @mbggenerated
     */
    public Integer getJiecunState() {
        return jiecunState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_state
     *
     * @param jiecunState the value for tab_hsf_jiecun.jiecun_state
     *
     * @mbggenerated
     */
    public void setJiecunState(Integer jiecunState) {
        this.jiecunState = jiecunState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_number
     *
     * @return the value of tab_hsf_jiecun.jiecun_number
     *
     * @mbggenerated
     */
    public Integer getJiecunNumber() {
        return jiecunNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_number
     *
     * @param jiecunNumber the value for tab_hsf_jiecun.jiecun_number
     *
     * @mbggenerated
     */
    public void setJiecunNumber(Integer jiecunNumber) {
        this.jiecunNumber = jiecunNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_bak1
     *
     * @return the value of tab_hsf_jiecun.jiecun_bak1
     *
     * @mbggenerated
     */
    public String getJiecunBak1() {
        return jiecunBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_bak1
     *
     * @param jiecunBak1 the value for tab_hsf_jiecun.jiecun_bak1
     *
     * @mbggenerated
     */
    public void setJiecunBak1(String jiecunBak1) {
        this.jiecunBak1 = jiecunBak1 == null ? null : jiecunBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_bak2
     *
     * @return the value of tab_hsf_jiecun.jiecun_bak2
     *
     * @mbggenerated
     */
    public String getJiecunBak2() {
        return jiecunBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_bak2
     *
     * @param jiecunBak2 the value for tab_hsf_jiecun.jiecun_bak2
     *
     * @mbggenerated
     */
    public void setJiecunBak2(String jiecunBak2) {
        this.jiecunBak2 = jiecunBak2 == null ? null : jiecunBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_jiecun.jiecun_bak3
     *
     * @return the value of tab_hsf_jiecun.jiecun_bak3
     *
     * @mbggenerated
     */
    public String getJiecunBak3() {
        return jiecunBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_jiecun.jiecun_bak3
     *
     * @param jiecunBak3 the value for tab_hsf_jiecun.jiecun_bak3
     *
     * @mbggenerated
     */
    public void setJiecunBak3(String jiecunBak3) {
        this.jiecunBak3 = jiecunBak3 == null ? null : jiecunBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabHsfJiecun other = (TabHsfJiecun) that;
        return (this.getJiecunId() == null ? other.getJiecunId() == null : this.getJiecunId().equals(other.getJiecunId()))
            && (this.getJiecunRs() == null ? other.getJiecunRs() == null : this.getJiecunRs().equals(other.getJiecunRs()))
            && (this.getJiecunMoney() == null ? other.getJiecunMoney() == null : this.getJiecunMoney().equals(other.getJiecunMoney()))
            && (this.getJiecunMonth() == null ? other.getJiecunMonth() == null : this.getJiecunMonth().equals(other.getJiecunMonth()))
            && (this.getJiecunAutotime() == null ? other.getJiecunAutotime() == null : this.getJiecunAutotime().equals(other.getJiecunAutotime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDepId() == null ? other.getDepId() == null : this.getDepId().equals(other.getDepId()))
            && (this.getJiecunState() == null ? other.getJiecunState() == null : this.getJiecunState().equals(other.getJiecunState()))
            && (this.getJiecunNumber() == null ? other.getJiecunNumber() == null : this.getJiecunNumber().equals(other.getJiecunNumber()))
            && (this.getJiecunBak1() == null ? other.getJiecunBak1() == null : this.getJiecunBak1().equals(other.getJiecunBak1()))
            && (this.getJiecunBak2() == null ? other.getJiecunBak2() == null : this.getJiecunBak2().equals(other.getJiecunBak2()))
            && (this.getJiecunBak3() == null ? other.getJiecunBak3() == null : this.getJiecunBak3().equals(other.getJiecunBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJiecunId() == null) ? 0 : getJiecunId().hashCode());
        result = prime * result + ((getJiecunRs() == null) ? 0 : getJiecunRs().hashCode());
        result = prime * result + ((getJiecunMoney() == null) ? 0 : getJiecunMoney().hashCode());
        result = prime * result + ((getJiecunMonth() == null) ? 0 : getJiecunMonth().hashCode());
        result = prime * result + ((getJiecunAutotime() == null) ? 0 : getJiecunAutotime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDepId() == null) ? 0 : getDepId().hashCode());
        result = prime * result + ((getJiecunState() == null) ? 0 : getJiecunState().hashCode());
        result = prime * result + ((getJiecunNumber() == null) ? 0 : getJiecunNumber().hashCode());
        result = prime * result + ((getJiecunBak1() == null) ? 0 : getJiecunBak1().hashCode());
        result = prime * result + ((getJiecunBak2() == null) ? 0 : getJiecunBak2().hashCode());
        result = prime * result + ((getJiecunBak3() == null) ? 0 : getJiecunBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jiecunId=").append(jiecunId);
        sb.append(", jiecunRs=").append(jiecunRs);
        sb.append(", jiecunMoney=").append(jiecunMoney);
        sb.append(", jiecunMonth=").append(jiecunMonth);
        sb.append(", jiecunAutotime=").append(jiecunAutotime);
        sb.append(", userId=").append(userId);
        sb.append(", depId=").append(depId);
        sb.append(", jiecunState=").append(jiecunState);
        sb.append(", jiecunNumber=").append(jiecunNumber);
        sb.append(", jiecunBak1=").append(jiecunBak1);
        sb.append(", jiecunBak2=").append(jiecunBak2);
        sb.append(", jiecunBak3=").append(jiecunBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}