package com.sc.dmh.beans;

import java.io.Serializable;

public class TabHsfSc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_sc.sc_id
     *
     * @mbggenerated
     */
    private Integer scId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_sc.sc_name
     *
     * @mbggenerated
     */
    private String scName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_sc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_sc.sc_id
     *
     * @return the value of tab_hsf_sc.sc_id
     *
     * @mbggenerated
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_sc.sc_id
     *
     * @param scId the value for tab_hsf_sc.sc_id
     *
     * @mbggenerated
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_sc.sc_name
     *
     * @return the value of tab_hsf_sc.sc_name
     *
     * @mbggenerated
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_sc.sc_name
     *
     * @param scName the value for tab_hsf_sc.sc_name
     *
     * @mbggenerated
     */
    public void setScName(String scName) {
        this.scName = scName == null ? null : scName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_sc
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabHsfSc other = (TabHsfSc) that;
        return (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getScName() == null ? other.getScName() == null : this.getScName().equals(other.getScName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_sc
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getScName() == null) ? 0 : getScName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_sc
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scId=").append(scId);
        sb.append(", scName=").append(scName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}