package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TabHsfShouru implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_id
     *
     * @mbggenerated
     */
    private Integer shouruId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_money
     *
     * @mbggenerated
     */
    private BigDecimal shouruMoney= new BigDecimal("0.00");

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_date
     *
     * @mbggenerated
     */
    private Date shouruDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_autodate
     *
     * @mbggenerated
     */
    private Date shouruAutodate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_beizu
     *
     * @mbggenerated
     */
    private String shouruBeizu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.dep_id
     *
     * @mbggenerated
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.srtype_id
     *
     * @mbggenerated
     */
    private Integer srtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_state
     *
     * @mbggenerated
     */
    private Integer shouruState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_bak1
     *
     * @mbggenerated
     */
    private String shouruBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_bak2
     *
     * @mbggenerated
     */
    private String shouruBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_shouru.shouru_bak3
     *
     * @mbggenerated
     */
    private String shouruBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_shouru
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_id
     *
     * @return the value of tab_hsf_shouru.shouru_id
     *
     * @mbggenerated
     */
    public Integer getShouruId() {
        return shouruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_id
     *
     * @param shouruId the value for tab_hsf_shouru.shouru_id
     *
     * @mbggenerated
     */
    public void setShouruId(Integer shouruId) {
        this.shouruId = shouruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_money
     *
     * @return the value of tab_hsf_shouru.shouru_money
     *
     * @mbggenerated
     */
    public BigDecimal getShouruMoney() {
        return shouruMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_money
     *
     * @param shouruMoney the value for tab_hsf_shouru.shouru_money
     *
     * @mbggenerated
     */
    public void setShouruMoney(BigDecimal shouruMoney) {
        this.shouruMoney = shouruMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_date
     *
     * @return the value of tab_hsf_shouru.shouru_date
     *
     * @mbggenerated
     */
    public Date getShouruDate() {
        return shouruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_date
     *
     * @param shouruDate the value for tab_hsf_shouru.shouru_date
     *
     * @mbggenerated
     */
    public void setShouruDate(Date shouruDate) {
        this.shouruDate = shouruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_autodate
     *
     * @return the value of tab_hsf_shouru.shouru_autodate
     *
     * @mbggenerated
     */
    public Date getShouruAutodate() {
        return shouruAutodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_autodate
     *
     * @param shouruAutodate the value for tab_hsf_shouru.shouru_autodate
     *
     * @mbggenerated
     */
    public void setShouruAutodate(Date shouruAutodate) {
        this.shouruAutodate = shouruAutodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_beizu
     *
     * @return the value of tab_hsf_shouru.shouru_beizu
     *
     * @mbggenerated
     */
    public String getShouruBeizu() {
        return shouruBeizu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_beizu
     *
     * @param shouruBeizu the value for tab_hsf_shouru.shouru_beizu
     *
     * @mbggenerated
     */
    public void setShouruBeizu(String shouruBeizu) {
        this.shouruBeizu = shouruBeizu == null ? null : shouruBeizu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.user_id
     *
     * @return the value of tab_hsf_shouru.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.user_id
     *
     * @param userId the value for tab_hsf_shouru.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.dep_id
     *
     * @return the value of tab_hsf_shouru.dep_id
     *
     * @mbggenerated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.dep_id
     *
     * @param depId the value for tab_hsf_shouru.dep_id
     *
     * @mbggenerated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.srtype_id
     *
     * @return the value of tab_hsf_shouru.srtype_id
     *
     * @mbggenerated
     */
    public Integer getSrtypeId() {
        return srtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.srtype_id
     *
     * @param srtypeId the value for tab_hsf_shouru.srtype_id
     *
     * @mbggenerated
     */
    public void setSrtypeId(Integer srtypeId) {
        this.srtypeId = srtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_state
     *
     * @return the value of tab_hsf_shouru.shouru_state
     *
     * @mbggenerated
     */
    public Integer getShouruState() {
        return shouruState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_state
     *
     * @param shouruState the value for tab_hsf_shouru.shouru_state
     *
     * @mbggenerated
     */
    public void setShouruState(Integer shouruState) {
        this.shouruState = shouruState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_bak1
     *
     * @return the value of tab_hsf_shouru.shouru_bak1
     *
     * @mbggenerated
     */
    public String getShouruBak1() {
        return shouruBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_bak1
     *
     * @param shouruBak1 the value for tab_hsf_shouru.shouru_bak1
     *
     * @mbggenerated
     */
    public void setShouruBak1(String shouruBak1) {
        this.shouruBak1 = shouruBak1 == null ? null : shouruBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_bak2
     *
     * @return the value of tab_hsf_shouru.shouru_bak2
     *
     * @mbggenerated
     */
    public String getShouruBak2() {
        return shouruBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_bak2
     *
     * @param shouruBak2 the value for tab_hsf_shouru.shouru_bak2
     *
     * @mbggenerated
     */
    public void setShouruBak2(String shouruBak2) {
        this.shouruBak2 = shouruBak2 == null ? null : shouruBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_shouru.shouru_bak3
     *
     * @return the value of tab_hsf_shouru.shouru_bak3
     *
     * @mbggenerated
     */
    public String getShouruBak3() {
        return shouruBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_shouru.shouru_bak3
     *
     * @param shouruBak3 the value for tab_hsf_shouru.shouru_bak3
     *
     * @mbggenerated
     */
    public void setShouruBak3(String shouruBak3) {
        this.shouruBak3 = shouruBak3 == null ? null : shouruBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_shouru
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabHsfShouru other = (TabHsfShouru) that;
        return (this.getShouruId() == null ? other.getShouruId() == null : this.getShouruId().equals(other.getShouruId()))
            && (this.getShouruMoney() == null ? other.getShouruMoney() == null : this.getShouruMoney().equals(other.getShouruMoney()))
            && (this.getShouruDate() == null ? other.getShouruDate() == null : this.getShouruDate().equals(other.getShouruDate()))
            && (this.getShouruAutodate() == null ? other.getShouruAutodate() == null : this.getShouruAutodate().equals(other.getShouruAutodate()))
            && (this.getShouruBeizu() == null ? other.getShouruBeizu() == null : this.getShouruBeizu().equals(other.getShouruBeizu()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDepId() == null ? other.getDepId() == null : this.getDepId().equals(other.getDepId()))
            && (this.getSrtypeId() == null ? other.getSrtypeId() == null : this.getSrtypeId().equals(other.getSrtypeId()))
            && (this.getShouruState() == null ? other.getShouruState() == null : this.getShouruState().equals(other.getShouruState()))
            && (this.getShouruBak1() == null ? other.getShouruBak1() == null : this.getShouruBak1().equals(other.getShouruBak1()))
            && (this.getShouruBak2() == null ? other.getShouruBak2() == null : this.getShouruBak2().equals(other.getShouruBak2()))
            && (this.getShouruBak3() == null ? other.getShouruBak3() == null : this.getShouruBak3().equals(other.getShouruBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_shouru
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShouruId() == null) ? 0 : getShouruId().hashCode());
        result = prime * result + ((getShouruMoney() == null) ? 0 : getShouruMoney().hashCode());
        result = prime * result + ((getShouruDate() == null) ? 0 : getShouruDate().hashCode());
        result = prime * result + ((getShouruAutodate() == null) ? 0 : getShouruAutodate().hashCode());
        result = prime * result + ((getShouruBeizu() == null) ? 0 : getShouruBeizu().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDepId() == null) ? 0 : getDepId().hashCode());
        result = prime * result + ((getSrtypeId() == null) ? 0 : getSrtypeId().hashCode());
        result = prime * result + ((getShouruState() == null) ? 0 : getShouruState().hashCode());
        result = prime * result + ((getShouruBak1() == null) ? 0 : getShouruBak1().hashCode());
        result = prime * result + ((getShouruBak2() == null) ? 0 : getShouruBak2().hashCode());
        result = prime * result + ((getShouruBak3() == null) ? 0 : getShouruBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_shouru
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shouruId=").append(shouruId);
        sb.append(", shouruMoney=").append(shouruMoney);
        sb.append(", shouruDate=").append(shouruDate);
        sb.append(", shouruAutodate=").append(shouruAutodate);
        sb.append(", shouruBeizu=").append(shouruBeizu);
        sb.append(", userId=").append(userId);
        sb.append(", depId=").append(depId);
        sb.append(", srtypeId=").append(srtypeId);
        sb.append(", shouruState=").append(shouruState);
        sb.append(", shouruBak1=").append(shouruBak1);
        sb.append(", shouruBak2=").append(shouruBak2);
        sb.append(", shouruBak3=").append(shouruBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}