package com.sc.dmh.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TabHsfJiecunExample {
    
	
	
	/**
	 * 手工添加分页变量开始
	 */
	private int startRow;
	private int pageSize;
	
	
	public int getStartRow() {
		return startRow;
	}

	public void setStartRow(int startRow) {
		this.startRow = startRow;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}
	/**
	 * 手工添加分页变量结束
	
	
	
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public TabHsfJiecunExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJiecunIdIsNull() {
            addCriterion("jiecun_id is null");
            return (Criteria) this;
        }

        public Criteria andJiecunIdIsNotNull() {
            addCriterion("jiecun_id is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunIdEqualTo(Integer value) {
            addCriterion("jiecun_id =", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdNotEqualTo(Integer value) {
            addCriterion("jiecun_id <>", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdGreaterThan(Integer value) {
            addCriterion("jiecun_id >", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiecun_id >=", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdLessThan(Integer value) {
            addCriterion("jiecun_id <", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdLessThanOrEqualTo(Integer value) {
            addCriterion("jiecun_id <=", value, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdIn(List<Integer> values) {
            addCriterion("jiecun_id in", values, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdNotIn(List<Integer> values) {
            addCriterion("jiecun_id not in", values, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_id between", value1, value2, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunIdNotBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_id not between", value1, value2, "jiecunId");
            return (Criteria) this;
        }

        public Criteria andJiecunRsIsNull() {
            addCriterion("jiecun_rs is null");
            return (Criteria) this;
        }

        public Criteria andJiecunRsIsNotNull() {
            addCriterion("jiecun_rs is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunRsEqualTo(Integer value) {
            addCriterion("jiecun_rs =", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsNotEqualTo(Integer value) {
            addCriterion("jiecun_rs <>", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsGreaterThan(Integer value) {
            addCriterion("jiecun_rs >", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiecun_rs >=", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsLessThan(Integer value) {
            addCriterion("jiecun_rs <", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsLessThanOrEqualTo(Integer value) {
            addCriterion("jiecun_rs <=", value, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsIn(List<Integer> values) {
            addCriterion("jiecun_rs in", values, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsNotIn(List<Integer> values) {
            addCriterion("jiecun_rs not in", values, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_rs between", value1, value2, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunRsNotBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_rs not between", value1, value2, "jiecunRs");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyIsNull() {
            addCriterion("jiecun_money is null");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyIsNotNull() {
            addCriterion("jiecun_money is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyEqualTo(BigDecimal value) {
            addCriterion("jiecun_money =", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyNotEqualTo(BigDecimal value) {
            addCriterion("jiecun_money <>", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyGreaterThan(BigDecimal value) {
            addCriterion("jiecun_money >", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("jiecun_money >=", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyLessThan(BigDecimal value) {
            addCriterion("jiecun_money <", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("jiecun_money <=", value, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyIn(List<BigDecimal> values) {
            addCriterion("jiecun_money in", values, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyNotIn(List<BigDecimal> values) {
            addCriterion("jiecun_money not in", values, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiecun_money between", value1, value2, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiecun_money not between", value1, value2, "jiecunMoney");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthIsNull() {
            addCriterion("jiecun_month is null");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthIsNotNull() {
            addCriterion("jiecun_month is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthEqualTo(Date value) {
            addCriterion("jiecun_month =", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthNotEqualTo(Date value) {
            addCriterion("jiecun_month <>", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthGreaterThan(Date value) {
            addCriterion("jiecun_month >", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthGreaterThanOrEqualTo(Date value) {
            addCriterion("jiecun_month >=", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthLessThan(Date value) {
            addCriterion("jiecun_month <", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthLessThanOrEqualTo(Date value) {
            addCriterion("jiecun_month <=", value, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthIn(List<Date> values) {
            addCriterion("jiecun_month in", values, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthNotIn(List<Date> values) {
            addCriterion("jiecun_month not in", values, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthBetween(Date value1, Date value2) {
            addCriterion("jiecun_month between", value1, value2, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunMonthNotBetween(Date value1, Date value2) {
            addCriterion("jiecun_month not between", value1, value2, "jiecunMonth");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeIsNull() {
            addCriterion("jiecun_autotime is null");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeIsNotNull() {
            addCriterion("jiecun_autotime is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeEqualTo(Date value) {
            addCriterion("jiecun_autotime =", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeNotEqualTo(Date value) {
            addCriterion("jiecun_autotime <>", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeGreaterThan(Date value) {
            addCriterion("jiecun_autotime >", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeGreaterThanOrEqualTo(Date value) {
            addCriterion("jiecun_autotime >=", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeLessThan(Date value) {
            addCriterion("jiecun_autotime <", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeLessThanOrEqualTo(Date value) {
            addCriterion("jiecun_autotime <=", value, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeIn(List<Date> values) {
            addCriterion("jiecun_autotime in", values, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeNotIn(List<Date> values) {
            addCriterion("jiecun_autotime not in", values, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeBetween(Date value1, Date value2) {
            addCriterion("jiecun_autotime between", value1, value2, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andJiecunAutotimeNotBetween(Date value1, Date value2) {
            addCriterion("jiecun_autotime not between", value1, value2, "jiecunAutotime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDepIdIsNull() {
            addCriterion("dep_id is null");
            return (Criteria) this;
        }

        public Criteria andDepIdIsNotNull() {
            addCriterion("dep_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepIdEqualTo(Integer value) {
            addCriterion("dep_id =", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotEqualTo(Integer value) {
            addCriterion("dep_id <>", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdGreaterThan(Integer value) {
            addCriterion("dep_id >", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dep_id >=", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdLessThan(Integer value) {
            addCriterion("dep_id <", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdLessThanOrEqualTo(Integer value) {
            addCriterion("dep_id <=", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdIn(List<Integer> values) {
            addCriterion("dep_id in", values, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotIn(List<Integer> values) {
            addCriterion("dep_id not in", values, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdBetween(Integer value1, Integer value2) {
            addCriterion("dep_id between", value1, value2, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dep_id not between", value1, value2, "depId");
            return (Criteria) this;
        }

        public Criteria andJiecunStateIsNull() {
            addCriterion("jiecun_state is null");
            return (Criteria) this;
        }

        public Criteria andJiecunStateIsNotNull() {
            addCriterion("jiecun_state is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunStateEqualTo(Integer value) {
            addCriterion("jiecun_state =", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateNotEqualTo(Integer value) {
            addCriterion("jiecun_state <>", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateGreaterThan(Integer value) {
            addCriterion("jiecun_state >", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiecun_state >=", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateLessThan(Integer value) {
            addCriterion("jiecun_state <", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateLessThanOrEqualTo(Integer value) {
            addCriterion("jiecun_state <=", value, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateIn(List<Integer> values) {
            addCriterion("jiecun_state in", values, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateNotIn(List<Integer> values) {
            addCriterion("jiecun_state not in", values, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_state between", value1, value2, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunStateNotBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_state not between", value1, value2, "jiecunState");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberIsNull() {
            addCriterion("jiecun_number is null");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberIsNotNull() {
            addCriterion("jiecun_number is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberEqualTo(Integer value) {
            addCriterion("jiecun_number =", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberNotEqualTo(Integer value) {
            addCriterion("jiecun_number <>", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberGreaterThan(Integer value) {
            addCriterion("jiecun_number >", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiecun_number >=", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberLessThan(Integer value) {
            addCriterion("jiecun_number <", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberLessThanOrEqualTo(Integer value) {
            addCriterion("jiecun_number <=", value, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberIn(List<Integer> values) {
            addCriterion("jiecun_number in", values, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberNotIn(List<Integer> values) {
            addCriterion("jiecun_number not in", values, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_number between", value1, value2, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("jiecun_number not between", value1, value2, "jiecunNumber");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1IsNull() {
            addCriterion("jiecun_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1IsNotNull() {
            addCriterion("jiecun_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1EqualTo(String value) {
            addCriterion("jiecun_bak1 =", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1NotEqualTo(String value) {
            addCriterion("jiecun_bak1 <>", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1GreaterThan(String value) {
            addCriterion("jiecun_bak1 >", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1GreaterThanOrEqualTo(String value) {
            addCriterion("jiecun_bak1 >=", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1LessThan(String value) {
            addCriterion("jiecun_bak1 <", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1LessThanOrEqualTo(String value) {
            addCriterion("jiecun_bak1 <=", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1Like(String value) {
            addCriterion("jiecun_bak1 like", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1NotLike(String value) {
            addCriterion("jiecun_bak1 not like", value, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1In(List<String> values) {
            addCriterion("jiecun_bak1 in", values, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1NotIn(List<String> values) {
            addCriterion("jiecun_bak1 not in", values, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1Between(String value1, String value2) {
            addCriterion("jiecun_bak1 between", value1, value2, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak1NotBetween(String value1, String value2) {
            addCriterion("jiecun_bak1 not between", value1, value2, "jiecunBak1");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2IsNull() {
            addCriterion("jiecun_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2IsNotNull() {
            addCriterion("jiecun_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2EqualTo(String value) {
            addCriterion("jiecun_bak2 =", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2NotEqualTo(String value) {
            addCriterion("jiecun_bak2 <>", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2GreaterThan(String value) {
            addCriterion("jiecun_bak2 >", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2GreaterThanOrEqualTo(String value) {
            addCriterion("jiecun_bak2 >=", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2LessThan(String value) {
            addCriterion("jiecun_bak2 <", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2LessThanOrEqualTo(String value) {
            addCriterion("jiecun_bak2 <=", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2Like(String value) {
            addCriterion("jiecun_bak2 like", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2NotLike(String value) {
            addCriterion("jiecun_bak2 not like", value, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2In(List<String> values) {
            addCriterion("jiecun_bak2 in", values, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2NotIn(List<String> values) {
            addCriterion("jiecun_bak2 not in", values, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2Between(String value1, String value2) {
            addCriterion("jiecun_bak2 between", value1, value2, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak2NotBetween(String value1, String value2) {
            addCriterion("jiecun_bak2 not between", value1, value2, "jiecunBak2");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3IsNull() {
            addCriterion("jiecun_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3IsNotNull() {
            addCriterion("jiecun_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3EqualTo(String value) {
            addCriterion("jiecun_bak3 =", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3NotEqualTo(String value) {
            addCriterion("jiecun_bak3 <>", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3GreaterThan(String value) {
            addCriterion("jiecun_bak3 >", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3GreaterThanOrEqualTo(String value) {
            addCriterion("jiecun_bak3 >=", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3LessThan(String value) {
            addCriterion("jiecun_bak3 <", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3LessThanOrEqualTo(String value) {
            addCriterion("jiecun_bak3 <=", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3Like(String value) {
            addCriterion("jiecun_bak3 like", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3NotLike(String value) {
            addCriterion("jiecun_bak3 not like", value, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3In(List<String> values) {
            addCriterion("jiecun_bak3 in", values, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3NotIn(List<String> values) {
            addCriterion("jiecun_bak3 not in", values, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3Between(String value1, String value2) {
            addCriterion("jiecun_bak3 between", value1, value2, "jiecunBak3");
            return (Criteria) this;
        }

        public Criteria andJiecunBak3NotBetween(String value1, String value2) {
            addCriterion("jiecun_bak3 not between", value1, value2, "jiecunBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_jiecun
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}