package com.sc.dmh.beans;

import java.io.Serializable;
import java.util.Date;

public class TabHsfPerson implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_id
     *
     * @mbggenerated
     */
    private Integer personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_in
     *
     * @mbggenerated
     */
    private Integer personIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_out
     *
     * @mbggenerated
     */
    private Integer personOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_time
     *
     * @mbggenerated
     */
    private Date personTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_autdate
     *
     * @mbggenerated
     */
    private Date personAutdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.dep_id
     *
     * @mbggenerated
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_state
     *
     * @mbggenerated
     */
    private Integer personState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_bak1
     *
     * @mbggenerated
     */
    private String personBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_bak2
     *
     * @mbggenerated
     */
    private String personBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_person.person_bak3
     *
     * @mbggenerated
     */
    private String personBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_person
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_id
     *
     * @return the value of tab_hsf_person.person_id
     *
     * @mbggenerated
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_id
     *
     * @param personId the value for tab_hsf_person.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_in
     *
     * @return the value of tab_hsf_person.person_in
     *
     * @mbggenerated
     */
    public Integer getPersonIn() {
        return personIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_in
     *
     * @param personIn the value for tab_hsf_person.person_in
     *
     * @mbggenerated
     */
    public void setPersonIn(Integer personIn) {
        this.personIn = personIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_out
     *
     * @return the value of tab_hsf_person.person_out
     *
     * @mbggenerated
     */
    public Integer getPersonOut() {
        return personOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_out
     *
     * @param personOut the value for tab_hsf_person.person_out
     *
     * @mbggenerated
     */
    public void setPersonOut(Integer personOut) {
        this.personOut = personOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_time
     *
     * @return the value of tab_hsf_person.person_time
     *
     * @mbggenerated
     */
    public Date getPersonTime() {
        return personTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_time
     *
     * @param personTime the value for tab_hsf_person.person_time
     *
     * @mbggenerated
     */
    public void setPersonTime(Date personTime) {
        this.personTime = personTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_autdate
     *
     * @return the value of tab_hsf_person.person_autdate
     *
     * @mbggenerated
     */
    public Date getPersonAutdate() {
        return personAutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_autdate
     *
     * @param personAutdate the value for tab_hsf_person.person_autdate
     *
     * @mbggenerated
     */
    public void setPersonAutdate(Date personAutdate) {
        this.personAutdate = personAutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.user_id
     *
     * @return the value of tab_hsf_person.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.user_id
     *
     * @param userId the value for tab_hsf_person.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.dep_id
     *
     * @return the value of tab_hsf_person.dep_id
     *
     * @mbggenerated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.dep_id
     *
     * @param depId the value for tab_hsf_person.dep_id
     *
     * @mbggenerated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_state
     *
     * @return the value of tab_hsf_person.person_state
     *
     * @mbggenerated
     */
    public Integer getPersonState() {
        return personState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_state
     *
     * @param personState the value for tab_hsf_person.person_state
     *
     * @mbggenerated
     */
    public void setPersonState(Integer personState) {
        this.personState = personState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_bak1
     *
     * @return the value of tab_hsf_person.person_bak1
     *
     * @mbggenerated
     */
    public String getPersonBak1() {
        return personBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_bak1
     *
     * @param personBak1 the value for tab_hsf_person.person_bak1
     *
     * @mbggenerated
     */
    public void setPersonBak1(String personBak1) {
        this.personBak1 = personBak1 == null ? null : personBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_bak2
     *
     * @return the value of tab_hsf_person.person_bak2
     *
     * @mbggenerated
     */
    public String getPersonBak2() {
        return personBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_bak2
     *
     * @param personBak2 the value for tab_hsf_person.person_bak2
     *
     * @mbggenerated
     */
    public void setPersonBak2(String personBak2) {
        this.personBak2 = personBak2 == null ? null : personBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_person.person_bak3
     *
     * @return the value of tab_hsf_person.person_bak3
     *
     * @mbggenerated
     */
    public String getPersonBak3() {
        return personBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_person.person_bak3
     *
     * @param personBak3 the value for tab_hsf_person.person_bak3
     *
     * @mbggenerated
     */
    public void setPersonBak3(String personBak3) {
        this.personBak3 = personBak3 == null ? null : personBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_person
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabHsfPerson other = (TabHsfPerson) that;
        return (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getPersonIn() == null ? other.getPersonIn() == null : this.getPersonIn().equals(other.getPersonIn()))
            && (this.getPersonOut() == null ? other.getPersonOut() == null : this.getPersonOut().equals(other.getPersonOut()))
            && (this.getPersonTime() == null ? other.getPersonTime() == null : this.getPersonTime().equals(other.getPersonTime()))
            && (this.getPersonAutdate() == null ? other.getPersonAutdate() == null : this.getPersonAutdate().equals(other.getPersonAutdate()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDepId() == null ? other.getDepId() == null : this.getDepId().equals(other.getDepId()))
            && (this.getPersonState() == null ? other.getPersonState() == null : this.getPersonState().equals(other.getPersonState()))
            && (this.getPersonBak1() == null ? other.getPersonBak1() == null : this.getPersonBak1().equals(other.getPersonBak1()))
            && (this.getPersonBak2() == null ? other.getPersonBak2() == null : this.getPersonBak2().equals(other.getPersonBak2()))
            && (this.getPersonBak3() == null ? other.getPersonBak3() == null : this.getPersonBak3().equals(other.getPersonBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_person
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getPersonIn() == null) ? 0 : getPersonIn().hashCode());
        result = prime * result + ((getPersonOut() == null) ? 0 : getPersonOut().hashCode());
        result = prime * result + ((getPersonTime() == null) ? 0 : getPersonTime().hashCode());
        result = prime * result + ((getPersonAutdate() == null) ? 0 : getPersonAutdate().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDepId() == null) ? 0 : getDepId().hashCode());
        result = prime * result + ((getPersonState() == null) ? 0 : getPersonState().hashCode());
        result = prime * result + ((getPersonBak1() == null) ? 0 : getPersonBak1().hashCode());
        result = prime * result + ((getPersonBak2() == null) ? 0 : getPersonBak2().hashCode());
        result = prime * result + ((getPersonBak3() == null) ? 0 : getPersonBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_person
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", personId=").append(personId);
        sb.append(", personIn=").append(personIn);
        sb.append(", personOut=").append(personOut);
        sb.append(", personTime=").append(personTime);
        sb.append(", personAutdate=").append(personAutdate);
        sb.append(", userId=").append(userId);
        sb.append(", depId=").append(depId);
        sb.append(", personState=").append(personState);
        sb.append(", personBak1=").append(personBak1);
        sb.append(", personBak2=").append(personBak2);
        sb.append(", personBak3=").append(personBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}