package com.sc.dmh.beans;

import java.io.Serializable;

public class TabHsfSrtype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_srtype.srtype_id
     *
     * @mbggenerated
     */
    private Integer srtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_srtype.srtype
     *
     * @mbggenerated
     */
    private String srtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_srtype.srtype_bak1
     *
     * @mbggenerated
     */
    private String srtypeBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_srtype.srtype_bak2
     *
     * @mbggenerated
     */
    private String srtypeBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_hsf_srtype.srtype_bak3
     *
     * @mbggenerated
     */
    private String srtypeBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_srtype.srtype_id
     *
     * @return the value of tab_hsf_srtype.srtype_id
     *
     * @mbggenerated
     */
    public Integer getSrtypeId() {
        return srtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_srtype.srtype_id
     *
     * @param srtypeId the value for tab_hsf_srtype.srtype_id
     *
     * @mbggenerated
     */
    public void setSrtypeId(Integer srtypeId) {
        this.srtypeId = srtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_srtype.srtype
     *
     * @return the value of tab_hsf_srtype.srtype
     *
     * @mbggenerated
     */
    public String getSrtype() {
        return srtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_srtype.srtype
     *
     * @param srtype the value for tab_hsf_srtype.srtype
     *
     * @mbggenerated
     */
    public void setSrtype(String srtype) {
        this.srtype = srtype == null ? null : srtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_srtype.srtype_bak1
     *
     * @return the value of tab_hsf_srtype.srtype_bak1
     *
     * @mbggenerated
     */
    public String getSrtypeBak1() {
        return srtypeBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_srtype.srtype_bak1
     *
     * @param srtypeBak1 the value for tab_hsf_srtype.srtype_bak1
     *
     * @mbggenerated
     */
    public void setSrtypeBak1(String srtypeBak1) {
        this.srtypeBak1 = srtypeBak1 == null ? null : srtypeBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_srtype.srtype_bak2
     *
     * @return the value of tab_hsf_srtype.srtype_bak2
     *
     * @mbggenerated
     */
    public String getSrtypeBak2() {
        return srtypeBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_srtype.srtype_bak2
     *
     * @param srtypeBak2 the value for tab_hsf_srtype.srtype_bak2
     *
     * @mbggenerated
     */
    public void setSrtypeBak2(String srtypeBak2) {
        this.srtypeBak2 = srtypeBak2 == null ? null : srtypeBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_hsf_srtype.srtype_bak3
     *
     * @return the value of tab_hsf_srtype.srtype_bak3
     *
     * @mbggenerated
     */
    public String getSrtypeBak3() {
        return srtypeBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_hsf_srtype.srtype_bak3
     *
     * @param srtypeBak3 the value for tab_hsf_srtype.srtype_bak3
     *
     * @mbggenerated
     */
    public void setSrtypeBak3(String srtypeBak3) {
        this.srtypeBak3 = srtypeBak3 == null ? null : srtypeBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabHsfSrtype other = (TabHsfSrtype) that;
        return (this.getSrtypeId() == null ? other.getSrtypeId() == null : this.getSrtypeId().equals(other.getSrtypeId()))
            && (this.getSrtype() == null ? other.getSrtype() == null : this.getSrtype().equals(other.getSrtype()))
            && (this.getSrtypeBak1() == null ? other.getSrtypeBak1() == null : this.getSrtypeBak1().equals(other.getSrtypeBak1()))
            && (this.getSrtypeBak2() == null ? other.getSrtypeBak2() == null : this.getSrtypeBak2().equals(other.getSrtypeBak2()))
            && (this.getSrtypeBak3() == null ? other.getSrtypeBak3() == null : this.getSrtypeBak3().equals(other.getSrtypeBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSrtypeId() == null) ? 0 : getSrtypeId().hashCode());
        result = prime * result + ((getSrtype() == null) ? 0 : getSrtype().hashCode());
        result = prime * result + ((getSrtypeBak1() == null) ? 0 : getSrtypeBak1().hashCode());
        result = prime * result + ((getSrtypeBak2() == null) ? 0 : getSrtypeBak2().hashCode());
        result = prime * result + ((getSrtypeBak3() == null) ? 0 : getSrtypeBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", srtypeId=").append(srtypeId);
        sb.append(", srtype=").append(srtype);
        sb.append(", srtypeBak1=").append(srtypeBak1);
        sb.append(", srtypeBak2=").append(srtypeBak2);
        sb.append(", srtypeBak3=").append(srtypeBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}