package com.sc.dmh.beans;

import java.util.ArrayList;
import java.util.List;

public class TabHsfSrtypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public TabHsfSrtypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSrtypeIdIsNull() {
            addCriterion("srtype_id is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdIsNotNull() {
            addCriterion("srtype_id is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdEqualTo(Integer value) {
            addCriterion("srtype_id =", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotEqualTo(Integer value) {
            addCriterion("srtype_id <>", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdGreaterThan(Integer value) {
            addCriterion("srtype_id >", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("srtype_id >=", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdLessThan(Integer value) {
            addCriterion("srtype_id <", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("srtype_id <=", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdIn(List<Integer> values) {
            addCriterion("srtype_id in", values, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotIn(List<Integer> values) {
            addCriterion("srtype_id not in", values, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdBetween(Integer value1, Integer value2) {
            addCriterion("srtype_id between", value1, value2, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("srtype_id not between", value1, value2, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIsNull() {
            addCriterion("srtype is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIsNotNull() {
            addCriterion("srtype is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeEqualTo(String value) {
            addCriterion("srtype =", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotEqualTo(String value) {
            addCriterion("srtype <>", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeGreaterThan(String value) {
            addCriterion("srtype >", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeGreaterThanOrEqualTo(String value) {
            addCriterion("srtype >=", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLessThan(String value) {
            addCriterion("srtype <", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLessThanOrEqualTo(String value) {
            addCriterion("srtype <=", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLike(String value) {
            addCriterion("srtype like", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotLike(String value) {
            addCriterion("srtype not like", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeIn(List<String> values) {
            addCriterion("srtype in", values, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotIn(List<String> values) {
            addCriterion("srtype not in", values, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeBetween(String value1, String value2) {
            addCriterion("srtype between", value1, value2, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotBetween(String value1, String value2) {
            addCriterion("srtype not between", value1, value2, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1IsNull() {
            addCriterion("srtype_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1IsNotNull() {
            addCriterion("srtype_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1EqualTo(String value) {
            addCriterion("srtype_bak1 =", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1NotEqualTo(String value) {
            addCriterion("srtype_bak1 <>", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1GreaterThan(String value) {
            addCriterion("srtype_bak1 >", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1GreaterThanOrEqualTo(String value) {
            addCriterion("srtype_bak1 >=", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1LessThan(String value) {
            addCriterion("srtype_bak1 <", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1LessThanOrEqualTo(String value) {
            addCriterion("srtype_bak1 <=", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1Like(String value) {
            addCriterion("srtype_bak1 like", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1NotLike(String value) {
            addCriterion("srtype_bak1 not like", value, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1In(List<String> values) {
            addCriterion("srtype_bak1 in", values, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1NotIn(List<String> values) {
            addCriterion("srtype_bak1 not in", values, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1Between(String value1, String value2) {
            addCriterion("srtype_bak1 between", value1, value2, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak1NotBetween(String value1, String value2) {
            addCriterion("srtype_bak1 not between", value1, value2, "srtypeBak1");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2IsNull() {
            addCriterion("srtype_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2IsNotNull() {
            addCriterion("srtype_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2EqualTo(String value) {
            addCriterion("srtype_bak2 =", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2NotEqualTo(String value) {
            addCriterion("srtype_bak2 <>", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2GreaterThan(String value) {
            addCriterion("srtype_bak2 >", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2GreaterThanOrEqualTo(String value) {
            addCriterion("srtype_bak2 >=", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2LessThan(String value) {
            addCriterion("srtype_bak2 <", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2LessThanOrEqualTo(String value) {
            addCriterion("srtype_bak2 <=", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2Like(String value) {
            addCriterion("srtype_bak2 like", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2NotLike(String value) {
            addCriterion("srtype_bak2 not like", value, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2In(List<String> values) {
            addCriterion("srtype_bak2 in", values, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2NotIn(List<String> values) {
            addCriterion("srtype_bak2 not in", values, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2Between(String value1, String value2) {
            addCriterion("srtype_bak2 between", value1, value2, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak2NotBetween(String value1, String value2) {
            addCriterion("srtype_bak2 not between", value1, value2, "srtypeBak2");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3IsNull() {
            addCriterion("srtype_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3IsNotNull() {
            addCriterion("srtype_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3EqualTo(String value) {
            addCriterion("srtype_bak3 =", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3NotEqualTo(String value) {
            addCriterion("srtype_bak3 <>", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3GreaterThan(String value) {
            addCriterion("srtype_bak3 >", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3GreaterThanOrEqualTo(String value) {
            addCriterion("srtype_bak3 >=", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3LessThan(String value) {
            addCriterion("srtype_bak3 <", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3LessThanOrEqualTo(String value) {
            addCriterion("srtype_bak3 <=", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3Like(String value) {
            addCriterion("srtype_bak3 like", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3NotLike(String value) {
            addCriterion("srtype_bak3 not like", value, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3In(List<String> values) {
            addCriterion("srtype_bak3 in", values, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3NotIn(List<String> values) {
            addCriterion("srtype_bak3 not in", values, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3Between(String value1, String value2) {
            addCriterion("srtype_bak3 between", value1, value2, "srtypeBak3");
            return (Criteria) this;
        }

        public Criteria andSrtypeBak3NotBetween(String value1, String value2) {
            addCriterion("srtype_bak3 not between", value1, value2, "srtypeBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_hsf_srtype
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}