package com.sc.dmh.beans;

import java.io.Serializable;

public class TabKemu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_id
     *
     * @mbggenerated
     */
    private Integer kemuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_dm
     *
     * @mbggenerated
     */
    private String kemuDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_bm
     *
     * @mbggenerated
     */
    private String kemuBm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_name
     *
     * @mbggenerated
     */
    private String kemuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_fpxm
     *
     * @mbggenerated
     */
    private String kemuFpxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_parentId
     *
     * @mbggenerated
     */
    private Integer kemuParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_collectionId
     *
     * @mbggenerated
     */
    private Integer kemuCollectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_layer
     *
     * @mbggenerated
     */
    private Integer kemuLayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_bak1
     *
     * @mbggenerated
     */
    private String kemuBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_bak2
     *
     * @mbggenerated
     */
    private String kemuBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_kemu.kemu_bak3
     *
     * @mbggenerated
     */
    private String kemuBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_id
     *
     * @return the value of tab_kemu.kemu_id
     *
     * @mbggenerated
     */
    public Integer getKemuId() {
        return kemuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_id
     *
     * @param kemuId the value for tab_kemu.kemu_id
     *
     * @mbggenerated
     */
    public void setKemuId(Integer kemuId) {
        this.kemuId = kemuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_dm
     *
     * @return the value of tab_kemu.kemu_dm
     *
     * @mbggenerated
     */
    public String getKemuDm() {
        return kemuDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_dm
     *
     * @param kemuDm the value for tab_kemu.kemu_dm
     *
     * @mbggenerated
     */
    public void setKemuDm(String kemuDm) {
        this.kemuDm = kemuDm == null ? null : kemuDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_bm
     *
     * @return the value of tab_kemu.kemu_bm
     *
     * @mbggenerated
     */
    public String getKemuBm() {
        return kemuBm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_bm
     *
     * @param kemuBm the value for tab_kemu.kemu_bm
     *
     * @mbggenerated
     */
    public void setKemuBm(String kemuBm) {
        this.kemuBm = kemuBm == null ? null : kemuBm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_name
     *
     * @return the value of tab_kemu.kemu_name
     *
     * @mbggenerated
     */
    public String getKemuName() {
        return kemuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_name
     *
     * @param kemuName the value for tab_kemu.kemu_name
     *
     * @mbggenerated
     */
    public void setKemuName(String kemuName) {
        this.kemuName = kemuName == null ? null : kemuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_fpxm
     *
     * @return the value of tab_kemu.kemu_fpxm
     *
     * @mbggenerated
     */
    public String getKemuFpxm() {
        return kemuFpxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_fpxm
     *
     * @param kemuFpxm the value for tab_kemu.kemu_fpxm
     *
     * @mbggenerated
     */
    public void setKemuFpxm(String kemuFpxm) {
        this.kemuFpxm = kemuFpxm == null ? null : kemuFpxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_parentId
     *
     * @return the value of tab_kemu.kemu_parentId
     *
     * @mbggenerated
     */
    public Integer getKemuParentid() {
        return kemuParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_parentId
     *
     * @param kemuParentid the value for tab_kemu.kemu_parentId
     *
     * @mbggenerated
     */
    public void setKemuParentid(Integer kemuParentid) {
        this.kemuParentid = kemuParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_collectionId
     *
     * @return the value of tab_kemu.kemu_collectionId
     *
     * @mbggenerated
     */
    public Integer getKemuCollectionid() {
        return kemuCollectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_collectionId
     *
     * @param kemuCollectionid the value for tab_kemu.kemu_collectionId
     *
     * @mbggenerated
     */
    public void setKemuCollectionid(Integer kemuCollectionid) {
        this.kemuCollectionid = kemuCollectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_layer
     *
     * @return the value of tab_kemu.kemu_layer
     *
     * @mbggenerated
     */
    public Integer getKemuLayer() {
        return kemuLayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_layer
     *
     * @param kemuLayer the value for tab_kemu.kemu_layer
     *
     * @mbggenerated
     */
    public void setKemuLayer(Integer kemuLayer) {
        this.kemuLayer = kemuLayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_bak1
     *
     * @return the value of tab_kemu.kemu_bak1
     *
     * @mbggenerated
     */
    public String getKemuBak1() {
        return kemuBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_bak1
     *
     * @param kemuBak1 the value for tab_kemu.kemu_bak1
     *
     * @mbggenerated
     */
    public void setKemuBak1(String kemuBak1) {
        this.kemuBak1 = kemuBak1 == null ? null : kemuBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_bak2
     *
     * @return the value of tab_kemu.kemu_bak2
     *
     * @mbggenerated
     */
    public String getKemuBak2() {
        return kemuBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_bak2
     *
     * @param kemuBak2 the value for tab_kemu.kemu_bak2
     *
     * @mbggenerated
     */
    public void setKemuBak2(String kemuBak2) {
        this.kemuBak2 = kemuBak2 == null ? null : kemuBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_kemu.kemu_bak3
     *
     * @return the value of tab_kemu.kemu_bak3
     *
     * @mbggenerated
     */
    public String getKemuBak3() {
        return kemuBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_kemu.kemu_bak3
     *
     * @param kemuBak3 the value for tab_kemu.kemu_bak3
     *
     * @mbggenerated
     */
    public void setKemuBak3(String kemuBak3) {
        this.kemuBak3 = kemuBak3 == null ? null : kemuBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabKemu other = (TabKemu) that;
        return (this.getKemuId() == null ? other.getKemuId() == null : this.getKemuId().equals(other.getKemuId()))
            && (this.getKemuDm() == null ? other.getKemuDm() == null : this.getKemuDm().equals(other.getKemuDm()))
            && (this.getKemuBm() == null ? other.getKemuBm() == null : this.getKemuBm().equals(other.getKemuBm()))
            && (this.getKemuName() == null ? other.getKemuName() == null : this.getKemuName().equals(other.getKemuName()))
            && (this.getKemuFpxm() == null ? other.getKemuFpxm() == null : this.getKemuFpxm().equals(other.getKemuFpxm()))
            && (this.getKemuParentid() == null ? other.getKemuParentid() == null : this.getKemuParentid().equals(other.getKemuParentid()))
            && (this.getKemuCollectionid() == null ? other.getKemuCollectionid() == null : this.getKemuCollectionid().equals(other.getKemuCollectionid()))
            && (this.getKemuLayer() == null ? other.getKemuLayer() == null : this.getKemuLayer().equals(other.getKemuLayer()))
            && (this.getKemuBak1() == null ? other.getKemuBak1() == null : this.getKemuBak1().equals(other.getKemuBak1()))
            && (this.getKemuBak2() == null ? other.getKemuBak2() == null : this.getKemuBak2().equals(other.getKemuBak2()))
            && (this.getKemuBak3() == null ? other.getKemuBak3() == null : this.getKemuBak3().equals(other.getKemuBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKemuId() == null) ? 0 : getKemuId().hashCode());
        result = prime * result + ((getKemuDm() == null) ? 0 : getKemuDm().hashCode());
        result = prime * result + ((getKemuBm() == null) ? 0 : getKemuBm().hashCode());
        result = prime * result + ((getKemuName() == null) ? 0 : getKemuName().hashCode());
        result = prime * result + ((getKemuFpxm() == null) ? 0 : getKemuFpxm().hashCode());
        result = prime * result + ((getKemuParentid() == null) ? 0 : getKemuParentid().hashCode());
        result = prime * result + ((getKemuCollectionid() == null) ? 0 : getKemuCollectionid().hashCode());
        result = prime * result + ((getKemuLayer() == null) ? 0 : getKemuLayer().hashCode());
        result = prime * result + ((getKemuBak1() == null) ? 0 : getKemuBak1().hashCode());
        result = prime * result + ((getKemuBak2() == null) ? 0 : getKemuBak2().hashCode());
        result = prime * result + ((getKemuBak3() == null) ? 0 : getKemuBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", kemuId=").append(kemuId);
        sb.append(", kemuDm=").append(kemuDm);
        sb.append(", kemuBm=").append(kemuBm);
        sb.append(", kemuName=").append(kemuName);
        sb.append(", kemuFpxm=").append(kemuFpxm);
        sb.append(", kemuParentid=").append(kemuParentid);
        sb.append(", kemuCollectionid=").append(kemuCollectionid);
        sb.append(", kemuLayer=").append(kemuLayer);
        sb.append(", kemuBak1=").append(kemuBak1);
        sb.append(", kemuBak2=").append(kemuBak2);
        sb.append(", kemuBak3=").append(kemuBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}