package com.sc.dmh.beans;

import java.util.ArrayList;
import java.util.List;

public class TabKemuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public TabKemuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKemuIdIsNull() {
            addCriterion("kemu_id is null");
            return (Criteria) this;
        }

        public Criteria andKemuIdIsNotNull() {
            addCriterion("kemu_id is not null");
            return (Criteria) this;
        }

        public Criteria andKemuIdEqualTo(Integer value) {
            addCriterion("kemu_id =", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdNotEqualTo(Integer value) {
            addCriterion("kemu_id <>", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdGreaterThan(Integer value) {
            addCriterion("kemu_id >", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("kemu_id >=", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdLessThan(Integer value) {
            addCriterion("kemu_id <", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdLessThanOrEqualTo(Integer value) {
            addCriterion("kemu_id <=", value, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdIn(List<Integer> values) {
            addCriterion("kemu_id in", values, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdNotIn(List<Integer> values) {
            addCriterion("kemu_id not in", values, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdBetween(Integer value1, Integer value2) {
            addCriterion("kemu_id between", value1, value2, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("kemu_id not between", value1, value2, "kemuId");
            return (Criteria) this;
        }

        public Criteria andKemuDmIsNull() {
            addCriterion("kemu_dm is null");
            return (Criteria) this;
        }

        public Criteria andKemuDmIsNotNull() {
            addCriterion("kemu_dm is not null");
            return (Criteria) this;
        }

        public Criteria andKemuDmEqualTo(String value) {
            addCriterion("kemu_dm =", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmNotEqualTo(String value) {
            addCriterion("kemu_dm <>", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmGreaterThan(String value) {
            addCriterion("kemu_dm >", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmGreaterThanOrEqualTo(String value) {
            addCriterion("kemu_dm >=", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmLessThan(String value) {
            addCriterion("kemu_dm <", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmLessThanOrEqualTo(String value) {
            addCriterion("kemu_dm <=", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmLike(String value) {
            addCriterion("kemu_dm like", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmNotLike(String value) {
            addCriterion("kemu_dm not like", value, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmIn(List<String> values) {
            addCriterion("kemu_dm in", values, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmNotIn(List<String> values) {
            addCriterion("kemu_dm not in", values, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmBetween(String value1, String value2) {
            addCriterion("kemu_dm between", value1, value2, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuDmNotBetween(String value1, String value2) {
            addCriterion("kemu_dm not between", value1, value2, "kemuDm");
            return (Criteria) this;
        }

        public Criteria andKemuBmIsNull() {
            addCriterion("kemu_bm is null");
            return (Criteria) this;
        }

        public Criteria andKemuBmIsNotNull() {
            addCriterion("kemu_bm is not null");
            return (Criteria) this;
        }

        public Criteria andKemuBmEqualTo(String value) {
            addCriterion("kemu_bm =", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmNotEqualTo(String value) {
            addCriterion("kemu_bm <>", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmGreaterThan(String value) {
            addCriterion("kemu_bm >", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmGreaterThanOrEqualTo(String value) {
            addCriterion("kemu_bm >=", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmLessThan(String value) {
            addCriterion("kemu_bm <", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmLessThanOrEqualTo(String value) {
            addCriterion("kemu_bm <=", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmLike(String value) {
            addCriterion("kemu_bm like", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmNotLike(String value) {
            addCriterion("kemu_bm not like", value, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmIn(List<String> values) {
            addCriterion("kemu_bm in", values, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmNotIn(List<String> values) {
            addCriterion("kemu_bm not in", values, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmBetween(String value1, String value2) {
            addCriterion("kemu_bm between", value1, value2, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuBmNotBetween(String value1, String value2) {
            addCriterion("kemu_bm not between", value1, value2, "kemuBm");
            return (Criteria) this;
        }

        public Criteria andKemuNameIsNull() {
            addCriterion("kemu_name is null");
            return (Criteria) this;
        }

        public Criteria andKemuNameIsNotNull() {
            addCriterion("kemu_name is not null");
            return (Criteria) this;
        }

        public Criteria andKemuNameEqualTo(String value) {
            addCriterion("kemu_name =", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameNotEqualTo(String value) {
            addCriterion("kemu_name <>", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameGreaterThan(String value) {
            addCriterion("kemu_name >", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameGreaterThanOrEqualTo(String value) {
            addCriterion("kemu_name >=", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameLessThan(String value) {
            addCriterion("kemu_name <", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameLessThanOrEqualTo(String value) {
            addCriterion("kemu_name <=", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameLike(String value) {
            addCriterion("kemu_name like", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameNotLike(String value) {
            addCriterion("kemu_name not like", value, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameIn(List<String> values) {
            addCriterion("kemu_name in", values, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameNotIn(List<String> values) {
            addCriterion("kemu_name not in", values, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameBetween(String value1, String value2) {
            addCriterion("kemu_name between", value1, value2, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuNameNotBetween(String value1, String value2) {
            addCriterion("kemu_name not between", value1, value2, "kemuName");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmIsNull() {
            addCriterion("kemu_fpxm is null");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmIsNotNull() {
            addCriterion("kemu_fpxm is not null");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmEqualTo(String value) {
            addCriterion("kemu_fpxm =", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmNotEqualTo(String value) {
            addCriterion("kemu_fpxm <>", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmGreaterThan(String value) {
            addCriterion("kemu_fpxm >", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmGreaterThanOrEqualTo(String value) {
            addCriterion("kemu_fpxm >=", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmLessThan(String value) {
            addCriterion("kemu_fpxm <", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmLessThanOrEqualTo(String value) {
            addCriterion("kemu_fpxm <=", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmLike(String value) {
            addCriterion("kemu_fpxm like", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmNotLike(String value) {
            addCriterion("kemu_fpxm not like", value, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmIn(List<String> values) {
            addCriterion("kemu_fpxm in", values, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmNotIn(List<String> values) {
            addCriterion("kemu_fpxm not in", values, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmBetween(String value1, String value2) {
            addCriterion("kemu_fpxm between", value1, value2, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuFpxmNotBetween(String value1, String value2) {
            addCriterion("kemu_fpxm not between", value1, value2, "kemuFpxm");
            return (Criteria) this;
        }

        public Criteria andKemuParentidIsNull() {
            addCriterion("kemu_parentId is null");
            return (Criteria) this;
        }

        public Criteria andKemuParentidIsNotNull() {
            addCriterion("kemu_parentId is not null");
            return (Criteria) this;
        }

        public Criteria andKemuParentidEqualTo(Integer value) {
            addCriterion("kemu_parentId =", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidNotEqualTo(Integer value) {
            addCriterion("kemu_parentId <>", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidGreaterThan(Integer value) {
            addCriterion("kemu_parentId >", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("kemu_parentId >=", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidLessThan(Integer value) {
            addCriterion("kemu_parentId <", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidLessThanOrEqualTo(Integer value) {
            addCriterion("kemu_parentId <=", value, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidIn(List<Integer> values) {
            addCriterion("kemu_parentId in", values, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidNotIn(List<Integer> values) {
            addCriterion("kemu_parentId not in", values, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidBetween(Integer value1, Integer value2) {
            addCriterion("kemu_parentId between", value1, value2, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuParentidNotBetween(Integer value1, Integer value2) {
            addCriterion("kemu_parentId not between", value1, value2, "kemuParentid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidIsNull() {
            addCriterion("kemu_collectionId is null");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidIsNotNull() {
            addCriterion("kemu_collectionId is not null");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidEqualTo(Integer value) {
            addCriterion("kemu_collectionId =", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidNotEqualTo(Integer value) {
            addCriterion("kemu_collectionId <>", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidGreaterThan(Integer value) {
            addCriterion("kemu_collectionId >", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("kemu_collectionId >=", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidLessThan(Integer value) {
            addCriterion("kemu_collectionId <", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidLessThanOrEqualTo(Integer value) {
            addCriterion("kemu_collectionId <=", value, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidIn(List<Integer> values) {
            addCriterion("kemu_collectionId in", values, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidNotIn(List<Integer> values) {
            addCriterion("kemu_collectionId not in", values, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidBetween(Integer value1, Integer value2) {
            addCriterion("kemu_collectionId between", value1, value2, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuCollectionidNotBetween(Integer value1, Integer value2) {
            addCriterion("kemu_collectionId not between", value1, value2, "kemuCollectionid");
            return (Criteria) this;
        }

        public Criteria andKemuLayerIsNull() {
            addCriterion("kemu_layer is null");
            return (Criteria) this;
        }

        public Criteria andKemuLayerIsNotNull() {
            addCriterion("kemu_layer is not null");
            return (Criteria) this;
        }

        public Criteria andKemuLayerEqualTo(Integer value) {
            addCriterion("kemu_layer =", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerNotEqualTo(Integer value) {
            addCriterion("kemu_layer <>", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerGreaterThan(Integer value) {
            addCriterion("kemu_layer >", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerGreaterThanOrEqualTo(Integer value) {
            addCriterion("kemu_layer >=", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerLessThan(Integer value) {
            addCriterion("kemu_layer <", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerLessThanOrEqualTo(Integer value) {
            addCriterion("kemu_layer <=", value, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerIn(List<Integer> values) {
            addCriterion("kemu_layer in", values, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerNotIn(List<Integer> values) {
            addCriterion("kemu_layer not in", values, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerBetween(Integer value1, Integer value2) {
            addCriterion("kemu_layer between", value1, value2, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuLayerNotBetween(Integer value1, Integer value2) {
            addCriterion("kemu_layer not between", value1, value2, "kemuLayer");
            return (Criteria) this;
        }

        public Criteria andKemuBak1IsNull() {
            addCriterion("kemu_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andKemuBak1IsNotNull() {
            addCriterion("kemu_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andKemuBak1EqualTo(String value) {
            addCriterion("kemu_bak1 =", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1NotEqualTo(String value) {
            addCriterion("kemu_bak1 <>", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1GreaterThan(String value) {
            addCriterion("kemu_bak1 >", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1GreaterThanOrEqualTo(String value) {
            addCriterion("kemu_bak1 >=", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1LessThan(String value) {
            addCriterion("kemu_bak1 <", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1LessThanOrEqualTo(String value) {
            addCriterion("kemu_bak1 <=", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1Like(String value) {
            addCriterion("kemu_bak1 like", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1NotLike(String value) {
            addCriterion("kemu_bak1 not like", value, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1In(List<String> values) {
            addCriterion("kemu_bak1 in", values, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1NotIn(List<String> values) {
            addCriterion("kemu_bak1 not in", values, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1Between(String value1, String value2) {
            addCriterion("kemu_bak1 between", value1, value2, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak1NotBetween(String value1, String value2) {
            addCriterion("kemu_bak1 not between", value1, value2, "kemuBak1");
            return (Criteria) this;
        }

        public Criteria andKemuBak2IsNull() {
            addCriterion("kemu_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andKemuBak2IsNotNull() {
            addCriterion("kemu_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andKemuBak2EqualTo(String value) {
            addCriterion("kemu_bak2 =", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2NotEqualTo(String value) {
            addCriterion("kemu_bak2 <>", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2GreaterThan(String value) {
            addCriterion("kemu_bak2 >", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2GreaterThanOrEqualTo(String value) {
            addCriterion("kemu_bak2 >=", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2LessThan(String value) {
            addCriterion("kemu_bak2 <", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2LessThanOrEqualTo(String value) {
            addCriterion("kemu_bak2 <=", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2Like(String value) {
            addCriterion("kemu_bak2 like", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2NotLike(String value) {
            addCriterion("kemu_bak2 not like", value, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2In(List<String> values) {
            addCriterion("kemu_bak2 in", values, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2NotIn(List<String> values) {
            addCriterion("kemu_bak2 not in", values, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2Between(String value1, String value2) {
            addCriterion("kemu_bak2 between", value1, value2, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak2NotBetween(String value1, String value2) {
            addCriterion("kemu_bak2 not between", value1, value2, "kemuBak2");
            return (Criteria) this;
        }

        public Criteria andKemuBak3IsNull() {
            addCriterion("kemu_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andKemuBak3IsNotNull() {
            addCriterion("kemu_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andKemuBak3EqualTo(String value) {
            addCriterion("kemu_bak3 =", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3NotEqualTo(String value) {
            addCriterion("kemu_bak3 <>", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3GreaterThan(String value) {
            addCriterion("kemu_bak3 >", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3GreaterThanOrEqualTo(String value) {
            addCriterion("kemu_bak3 >=", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3LessThan(String value) {
            addCriterion("kemu_bak3 <", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3LessThanOrEqualTo(String value) {
            addCriterion("kemu_bak3 <=", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3Like(String value) {
            addCriterion("kemu_bak3 like", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3NotLike(String value) {
            addCriterion("kemu_bak3 not like", value, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3In(List<String> values) {
            addCriterion("kemu_bak3 in", values, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3NotIn(List<String> values) {
            addCriterion("kemu_bak3 not in", values, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3Between(String value1, String value2) {
            addCriterion("kemu_bak3 between", value1, value2, "kemuBak3");
            return (Criteria) this;
        }

        public Criteria andKemuBak3NotBetween(String value1, String value2) {
            addCriterion("kemu_bak3 not between", value1, value2, "kemuBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_kemu
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_kemu
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}