package com.sc.dmh.beans;

import java.io.Serializable;

public class TabPiaoku implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_piaoku.piaoku_id
     *
     * @mbggenerated
     */
    private Integer piaokuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_piaoku.piaoku_
     *
     * @mbggenerated
     */
    private String piaoku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_piaoku
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_piaoku.piaoku_id
     *
     * @return the value of tab_piaoku.piaoku_id
     *
     * @mbggenerated
     */
    public Integer getPiaokuId() {
        return piaokuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_piaoku.piaoku_id
     *
     * @param piaokuId the value for tab_piaoku.piaoku_id
     *
     * @mbggenerated
     */
    public void setPiaokuId(Integer piaokuId) {
        this.piaokuId = piaokuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_piaoku.piaoku_
     *
     * @return the value of tab_piaoku.piaoku_
     *
     * @mbggenerated
     */
    public String getPiaoku() {
        return piaoku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_piaoku.piaoku_
     *
     * @param piaoku the value for tab_piaoku.piaoku_
     *
     * @mbggenerated
     */
    public void setPiaoku(String piaoku) {
        this.piaoku = piaoku == null ? null : piaoku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_piaoku
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabPiaoku other = (TabPiaoku) that;
        return (this.getPiaokuId() == null ? other.getPiaokuId() == null : this.getPiaokuId().equals(other.getPiaokuId()))
            && (this.getPiaoku() == null ? other.getPiaoku() == null : this.getPiaoku().equals(other.getPiaoku()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_piaoku
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPiaokuId() == null) ? 0 : getPiaokuId().hashCode());
        result = prime * result + ((getPiaoku() == null) ? 0 : getPiaoku().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_piaoku
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", piaokuId=").append(piaokuId);
        sb.append(", piaoku=").append(piaoku);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}