package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TabRpf implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.rpf_id
     *
     * @mbggenerated
     */
    private Integer rpfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.cz_id
     *
     * @mbggenerated
     */
    private Integer czId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.fp_number
     *
     * @mbggenerated
     */
    private Integer fpNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.sp_number
     *
     * @mbggenerated
     */
    private Integer spNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.fpl
     *
     * @mbggenerated
     */
    private Double fpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.fp_cb
     *
     * @mbggenerated
     */
    private BigDecimal fpCb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.sp_cb
     *
     * @mbggenerated
     */
    private BigDecimal spCb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.sj_cb
     *
     * @mbggenerated
     */
    private BigDecimal sjCb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.ticketTypes_id
     *
     * @mbggenerated
     */
    private Integer tickettypesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.in_date
     *
     * @mbggenerated
     */
    private Date inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.auto_date
     *
     * @mbggenerated
     */
    private Date autoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.rpf_bak1
     *
     * @mbggenerated
     */
    private String rpfBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.rpf_bak2
     *
     * @mbggenerated
     */
    private String rpfBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_rpf.rpf_bak3
     *
     * @mbggenerated
     */
    private String rpfBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.rpf_id
     *
     * @return the value of tab_rpf.rpf_id
     *
     * @mbggenerated
     */
    public Integer getRpfId() {
        return rpfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.rpf_id
     *
     * @param rpfId the value for tab_rpf.rpf_id
     *
     * @mbggenerated
     */
    public void setRpfId(Integer rpfId) {
        this.rpfId = rpfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.cz_id
     *
     * @return the value of tab_rpf.cz_id
     *
     * @mbggenerated
     */
    public Integer getCzId() {
        return czId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.cz_id
     *
     * @param czId the value for tab_rpf.cz_id
     *
     * @mbggenerated
     */
    public void setCzId(Integer czId) {
        this.czId = czId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.fp_number
     *
     * @return the value of tab_rpf.fp_number
     *
     * @mbggenerated
     */
    public Integer getFpNumber() {
        return fpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.fp_number
     *
     * @param fpNumber the value for tab_rpf.fp_number
     *
     * @mbggenerated
     */
    public void setFpNumber(Integer fpNumber) {
        this.fpNumber = fpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.sp_number
     *
     * @return the value of tab_rpf.sp_number
     *
     * @mbggenerated
     */
    public Integer getSpNumber() {
        return spNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.sp_number
     *
     * @param spNumber the value for tab_rpf.sp_number
     *
     * @mbggenerated
     */
    public void setSpNumber(Integer spNumber) {
        this.spNumber = spNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.fpl
     *
     * @return the value of tab_rpf.fpl
     *
     * @mbggenerated
     */
    public Double getFpl() {
        return fpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.fpl
     *
     * @param fpl the value for tab_rpf.fpl
     *
     * @mbggenerated
     */
    public void setFpl(Double fpl) {
        this.fpl = fpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.fp_cb
     *
     * @return the value of tab_rpf.fp_cb
     *
     * @mbggenerated
     */
    public BigDecimal getFpCb() {
        return fpCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.fp_cb
     *
     * @param fpCb the value for tab_rpf.fp_cb
     *
     * @mbggenerated
     */
    public void setFpCb(BigDecimal fpCb) {
        this.fpCb = fpCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.sp_cb
     *
     * @return the value of tab_rpf.sp_cb
     *
     * @mbggenerated
     */
    public BigDecimal getSpCb() {
        return spCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.sp_cb
     *
     * @param spCb the value for tab_rpf.sp_cb
     *
     * @mbggenerated
     */
    public void setSpCb(BigDecimal spCb) {
        this.spCb = spCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.sj_cb
     *
     * @return the value of tab_rpf.sj_cb
     *
     * @mbggenerated
     */
    public BigDecimal getSjCb() {
        return sjCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.sj_cb
     *
     * @param sjCb the value for tab_rpf.sj_cb
     *
     * @mbggenerated
     */
    public void setSjCb(BigDecimal sjCb) {
        this.sjCb = sjCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.ticketTypes_id
     *
     * @return the value of tab_rpf.ticketTypes_id
     *
     * @mbggenerated
     */
    public Integer getTickettypesId() {
        return tickettypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.ticketTypes_id
     *
     * @param tickettypesId the value for tab_rpf.ticketTypes_id
     *
     * @mbggenerated
     */
    public void setTickettypesId(Integer tickettypesId) {
        this.tickettypesId = tickettypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.in_date
     *
     * @return the value of tab_rpf.in_date
     *
     * @mbggenerated
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.in_date
     *
     * @param inDate the value for tab_rpf.in_date
     *
     * @mbggenerated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.auto_date
     *
     * @return the value of tab_rpf.auto_date
     *
     * @mbggenerated
     */
    public Date getAutoDate() {
        return autoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.auto_date
     *
     * @param autoDate the value for tab_rpf.auto_date
     *
     * @mbggenerated
     */
    public void setAutoDate(Date autoDate) {
        this.autoDate = autoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.rpf_bak1
     *
     * @return the value of tab_rpf.rpf_bak1
     *
     * @mbggenerated
     */
    public String getRpfBak1() {
        return rpfBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.rpf_bak1
     *
     * @param rpfBak1 the value for tab_rpf.rpf_bak1
     *
     * @mbggenerated
     */
    public void setRpfBak1(String rpfBak1) {
        this.rpfBak1 = rpfBak1 == null ? null : rpfBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.rpf_bak2
     *
     * @return the value of tab_rpf.rpf_bak2
     *
     * @mbggenerated
     */
    public String getRpfBak2() {
        return rpfBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.rpf_bak2
     *
     * @param rpfBak2 the value for tab_rpf.rpf_bak2
     *
     * @mbggenerated
     */
    public void setRpfBak2(String rpfBak2) {
        this.rpfBak2 = rpfBak2 == null ? null : rpfBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_rpf.rpf_bak3
     *
     * @return the value of tab_rpf.rpf_bak3
     *
     * @mbggenerated
     */
    public String getRpfBak3() {
        return rpfBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_rpf.rpf_bak3
     *
     * @param rpfBak3 the value for tab_rpf.rpf_bak3
     *
     * @mbggenerated
     */
    public void setRpfBak3(String rpfBak3) {
        this.rpfBak3 = rpfBak3 == null ? null : rpfBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabRpf other = (TabRpf) that;
        return (this.getRpfId() == null ? other.getRpfId() == null : this.getRpfId().equals(other.getRpfId()))
            && (this.getCzId() == null ? other.getCzId() == null : this.getCzId().equals(other.getCzId()))
            && (this.getFpNumber() == null ? other.getFpNumber() == null : this.getFpNumber().equals(other.getFpNumber()))
            && (this.getSpNumber() == null ? other.getSpNumber() == null : this.getSpNumber().equals(other.getSpNumber()))
            && (this.getFpl() == null ? other.getFpl() == null : this.getFpl().equals(other.getFpl()))
            && (this.getFpCb() == null ? other.getFpCb() == null : this.getFpCb().equals(other.getFpCb()))
            && (this.getSpCb() == null ? other.getSpCb() == null : this.getSpCb().equals(other.getSpCb()))
            && (this.getSjCb() == null ? other.getSjCb() == null : this.getSjCb().equals(other.getSjCb()))
            && (this.getTickettypesId() == null ? other.getTickettypesId() == null : this.getTickettypesId().equals(other.getTickettypesId()))
            && (this.getInDate() == null ? other.getInDate() == null : this.getInDate().equals(other.getInDate()))
            && (this.getAutoDate() == null ? other.getAutoDate() == null : this.getAutoDate().equals(other.getAutoDate()))
            && (this.getRpfBak1() == null ? other.getRpfBak1() == null : this.getRpfBak1().equals(other.getRpfBak1()))
            && (this.getRpfBak2() == null ? other.getRpfBak2() == null : this.getRpfBak2().equals(other.getRpfBak2()))
            && (this.getRpfBak3() == null ? other.getRpfBak3() == null : this.getRpfBak3().equals(other.getRpfBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRpfId() == null) ? 0 : getRpfId().hashCode());
        result = prime * result + ((getCzId() == null) ? 0 : getCzId().hashCode());
        result = prime * result + ((getFpNumber() == null) ? 0 : getFpNumber().hashCode());
        result = prime * result + ((getSpNumber() == null) ? 0 : getSpNumber().hashCode());
        result = prime * result + ((getFpl() == null) ? 0 : getFpl().hashCode());
        result = prime * result + ((getFpCb() == null) ? 0 : getFpCb().hashCode());
        result = prime * result + ((getSpCb() == null) ? 0 : getSpCb().hashCode());
        result = prime * result + ((getSjCb() == null) ? 0 : getSjCb().hashCode());
        result = prime * result + ((getTickettypesId() == null) ? 0 : getTickettypesId().hashCode());
        result = prime * result + ((getInDate() == null) ? 0 : getInDate().hashCode());
        result = prime * result + ((getAutoDate() == null) ? 0 : getAutoDate().hashCode());
        result = prime * result + ((getRpfBak1() == null) ? 0 : getRpfBak1().hashCode());
        result = prime * result + ((getRpfBak2() == null) ? 0 : getRpfBak2().hashCode());
        result = prime * result + ((getRpfBak3() == null) ? 0 : getRpfBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_rpf
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rpfId=").append(rpfId);
        sb.append(", czId=").append(czId);
        sb.append(", fpNumber=").append(fpNumber);
        sb.append(", spNumber=").append(spNumber);
        sb.append(", fpl=").append(fpl);
        sb.append(", fpCb=").append(fpCb);
        sb.append(", spCb=").append(spCb);
        sb.append(", sjCb=").append(sjCb);
        sb.append(", tickettypesId=").append(tickettypesId);
        sb.append(", inDate=").append(inDate);
        sb.append(", autoDate=").append(autoDate);
        sb.append(", rpfBak1=").append(rpfBak1);
        sb.append(", rpfBak2=").append(rpfBak2);
        sb.append(", rpfBak3=").append(rpfBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}