package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;

public class TabTickettypes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_id
     *
     * @mbggenerated
     */
    private Integer tickettypesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_price
     *
     * @mbggenerated
     */
    private BigDecimal tickettypesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_name
     *
     * @mbggenerated
     */
    private String tickettypesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_bak1
     *
     * @mbggenerated
     */
    private String tickettypesBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_bak2
     *
     * @mbggenerated
     */
    private String tickettypesBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tickettypes.ticketTypes_bka3
     *
     * @mbggenerated
     */
    private String tickettypesBka3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_id
     *
     * @return the value of tab_tickettypes.ticketTypes_id
     *
     * @mbggenerated
     */
    public Integer getTickettypesId() {
        return tickettypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_id
     *
     * @param tickettypesId the value for tab_tickettypes.ticketTypes_id
     *
     * @mbggenerated
     */
    public void setTickettypesId(Integer tickettypesId) {
        this.tickettypesId = tickettypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_price
     *
     * @return the value of tab_tickettypes.ticketTypes_price
     *
     * @mbggenerated
     */
    public BigDecimal getTickettypesPrice() {
        return tickettypesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_price
     *
     * @param tickettypesPrice the value for tab_tickettypes.ticketTypes_price
     *
     * @mbggenerated
     */
    public void setTickettypesPrice(BigDecimal tickettypesPrice) {
        this.tickettypesPrice = tickettypesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_name
     *
     * @return the value of tab_tickettypes.ticketTypes_name
     *
     * @mbggenerated
     */
    public String getTickettypesName() {
        return tickettypesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_name
     *
     * @param tickettypesName the value for tab_tickettypes.ticketTypes_name
     *
     * @mbggenerated
     */
    public void setTickettypesName(String tickettypesName) {
        this.tickettypesName = tickettypesName == null ? null : tickettypesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_bak1
     *
     * @return the value of tab_tickettypes.ticketTypes_bak1
     *
     * @mbggenerated
     */
    public String getTickettypesBak1() {
        return tickettypesBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_bak1
     *
     * @param tickettypesBak1 the value for tab_tickettypes.ticketTypes_bak1
     *
     * @mbggenerated
     */
    public void setTickettypesBak1(String tickettypesBak1) {
        this.tickettypesBak1 = tickettypesBak1 == null ? null : tickettypesBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_bak2
     *
     * @return the value of tab_tickettypes.ticketTypes_bak2
     *
     * @mbggenerated
     */
    public String getTickettypesBak2() {
        return tickettypesBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_bak2
     *
     * @param tickettypesBak2 the value for tab_tickettypes.ticketTypes_bak2
     *
     * @mbggenerated
     */
    public void setTickettypesBak2(String tickettypesBak2) {
        this.tickettypesBak2 = tickettypesBak2 == null ? null : tickettypesBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tickettypes.ticketTypes_bka3
     *
     * @return the value of tab_tickettypes.ticketTypes_bka3
     *
     * @mbggenerated
     */
    public String getTickettypesBka3() {
        return tickettypesBka3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tickettypes.ticketTypes_bka3
     *
     * @param tickettypesBka3 the value for tab_tickettypes.ticketTypes_bka3
     *
     * @mbggenerated
     */
    public void setTickettypesBka3(String tickettypesBka3) {
        this.tickettypesBka3 = tickettypesBka3 == null ? null : tickettypesBka3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabTickettypes other = (TabTickettypes) that;
        return (this.getTickettypesId() == null ? other.getTickettypesId() == null : this.getTickettypesId().equals(other.getTickettypesId()))
            && (this.getTickettypesPrice() == null ? other.getTickettypesPrice() == null : this.getTickettypesPrice().equals(other.getTickettypesPrice()))
            && (this.getTickettypesName() == null ? other.getTickettypesName() == null : this.getTickettypesName().equals(other.getTickettypesName()))
            && (this.getTickettypesBak1() == null ? other.getTickettypesBak1() == null : this.getTickettypesBak1().equals(other.getTickettypesBak1()))
            && (this.getTickettypesBak2() == null ? other.getTickettypesBak2() == null : this.getTickettypesBak2().equals(other.getTickettypesBak2()))
            && (this.getTickettypesBka3() == null ? other.getTickettypesBka3() == null : this.getTickettypesBka3().equals(other.getTickettypesBka3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTickettypesId() == null) ? 0 : getTickettypesId().hashCode());
        result = prime * result + ((getTickettypesPrice() == null) ? 0 : getTickettypesPrice().hashCode());
        result = prime * result + ((getTickettypesName() == null) ? 0 : getTickettypesName().hashCode());
        result = prime * result + ((getTickettypesBak1() == null) ? 0 : getTickettypesBak1().hashCode());
        result = prime * result + ((getTickettypesBak2() == null) ? 0 : getTickettypesBak2().hashCode());
        result = prime * result + ((getTickettypesBka3() == null) ? 0 : getTickettypesBka3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tickettypesId=").append(tickettypesId);
        sb.append(", tickettypesPrice=").append(tickettypesPrice);
        sb.append(", tickettypesName=").append(tickettypesName);
        sb.append(", tickettypesBak1=").append(tickettypesBak1);
        sb.append(", tickettypesBak2=").append(tickettypesBak2);
        sb.append(", tickettypesBka3=").append(tickettypesBka3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}