package com.sc.dmh.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TabTickettypesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public TabTickettypesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTickettypesIdIsNull() {
            addCriterion("ticketTypes_id is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdIsNotNull() {
            addCriterion("ticketTypes_id is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdEqualTo(Integer value) {
            addCriterion("ticketTypes_id =", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdNotEqualTo(Integer value) {
            addCriterion("ticketTypes_id <>", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdGreaterThan(Integer value) {
            addCriterion("ticketTypes_id >", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticketTypes_id >=", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdLessThan(Integer value) {
            addCriterion("ticketTypes_id <", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdLessThanOrEqualTo(Integer value) {
            addCriterion("ticketTypes_id <=", value, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdIn(List<Integer> values) {
            addCriterion("ticketTypes_id in", values, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdNotIn(List<Integer> values) {
            addCriterion("ticketTypes_id not in", values, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdBetween(Integer value1, Integer value2) {
            addCriterion("ticketTypes_id between", value1, value2, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ticketTypes_id not between", value1, value2, "tickettypesId");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceIsNull() {
            addCriterion("ticketTypes_price is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceIsNotNull() {
            addCriterion("ticketTypes_price is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceEqualTo(BigDecimal value) {
            addCriterion("ticketTypes_price =", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceNotEqualTo(BigDecimal value) {
            addCriterion("ticketTypes_price <>", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceGreaterThan(BigDecimal value) {
            addCriterion("ticketTypes_price >", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ticketTypes_price >=", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceLessThan(BigDecimal value) {
            addCriterion("ticketTypes_price <", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ticketTypes_price <=", value, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceIn(List<BigDecimal> values) {
            addCriterion("ticketTypes_price in", values, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceNotIn(List<BigDecimal> values) {
            addCriterion("ticketTypes_price not in", values, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticketTypes_price between", value1, value2, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticketTypes_price not between", value1, value2, "tickettypesPrice");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameIsNull() {
            addCriterion("ticketTypes_name is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameIsNotNull() {
            addCriterion("ticketTypes_name is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameEqualTo(String value) {
            addCriterion("ticketTypes_name =", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameNotEqualTo(String value) {
            addCriterion("ticketTypes_name <>", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameGreaterThan(String value) {
            addCriterion("ticketTypes_name >", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameGreaterThanOrEqualTo(String value) {
            addCriterion("ticketTypes_name >=", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameLessThan(String value) {
            addCriterion("ticketTypes_name <", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameLessThanOrEqualTo(String value) {
            addCriterion("ticketTypes_name <=", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameLike(String value) {
            addCriterion("ticketTypes_name like", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameNotLike(String value) {
            addCriterion("ticketTypes_name not like", value, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameIn(List<String> values) {
            addCriterion("ticketTypes_name in", values, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameNotIn(List<String> values) {
            addCriterion("ticketTypes_name not in", values, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameBetween(String value1, String value2) {
            addCriterion("ticketTypes_name between", value1, value2, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesNameNotBetween(String value1, String value2) {
            addCriterion("ticketTypes_name not between", value1, value2, "tickettypesName");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1IsNull() {
            addCriterion("ticketTypes_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1IsNotNull() {
            addCriterion("ticketTypes_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1EqualTo(String value) {
            addCriterion("ticketTypes_bak1 =", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1NotEqualTo(String value) {
            addCriterion("ticketTypes_bak1 <>", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1GreaterThan(String value) {
            addCriterion("ticketTypes_bak1 >", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1GreaterThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bak1 >=", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1LessThan(String value) {
            addCriterion("ticketTypes_bak1 <", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1LessThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bak1 <=", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1Like(String value) {
            addCriterion("ticketTypes_bak1 like", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1NotLike(String value) {
            addCriterion("ticketTypes_bak1 not like", value, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1In(List<String> values) {
            addCriterion("ticketTypes_bak1 in", values, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1NotIn(List<String> values) {
            addCriterion("ticketTypes_bak1 not in", values, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1Between(String value1, String value2) {
            addCriterion("ticketTypes_bak1 between", value1, value2, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak1NotBetween(String value1, String value2) {
            addCriterion("ticketTypes_bak1 not between", value1, value2, "tickettypesBak1");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2IsNull() {
            addCriterion("ticketTypes_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2IsNotNull() {
            addCriterion("ticketTypes_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2EqualTo(String value) {
            addCriterion("ticketTypes_bak2 =", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2NotEqualTo(String value) {
            addCriterion("ticketTypes_bak2 <>", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2GreaterThan(String value) {
            addCriterion("ticketTypes_bak2 >", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2GreaterThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bak2 >=", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2LessThan(String value) {
            addCriterion("ticketTypes_bak2 <", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2LessThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bak2 <=", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2Like(String value) {
            addCriterion("ticketTypes_bak2 like", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2NotLike(String value) {
            addCriterion("ticketTypes_bak2 not like", value, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2In(List<String> values) {
            addCriterion("ticketTypes_bak2 in", values, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2NotIn(List<String> values) {
            addCriterion("ticketTypes_bak2 not in", values, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2Between(String value1, String value2) {
            addCriterion("ticketTypes_bak2 between", value1, value2, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBak2NotBetween(String value1, String value2) {
            addCriterion("ticketTypes_bak2 not between", value1, value2, "tickettypesBak2");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3IsNull() {
            addCriterion("ticketTypes_bka3 is null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3IsNotNull() {
            addCriterion("ticketTypes_bka3 is not null");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3EqualTo(String value) {
            addCriterion("ticketTypes_bka3 =", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3NotEqualTo(String value) {
            addCriterion("ticketTypes_bka3 <>", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3GreaterThan(String value) {
            addCriterion("ticketTypes_bka3 >", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3GreaterThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bka3 >=", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3LessThan(String value) {
            addCriterion("ticketTypes_bka3 <", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3LessThanOrEqualTo(String value) {
            addCriterion("ticketTypes_bka3 <=", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3Like(String value) {
            addCriterion("ticketTypes_bka3 like", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3NotLike(String value) {
            addCriterion("ticketTypes_bka3 not like", value, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3In(List<String> values) {
            addCriterion("ticketTypes_bka3 in", values, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3NotIn(List<String> values) {
            addCriterion("ticketTypes_bka3 not in", values, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3Between(String value1, String value2) {
            addCriterion("ticketTypes_bka3 between", value1, value2, "tickettypesBka3");
            return (Criteria) this;
        }

        public Criteria andTickettypesBka3NotBetween(String value1, String value2) {
            addCriterion("ticketTypes_bka3 not between", value1, value2, "tickettypesBka3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_tickettypes
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_tickettypes
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}