package com.sc.dmh.beans;

import java.io.Serializable;

public class TabType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_text
     *
     * @mbggenerated
     */
    private String typeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_id
     *
     * @return the value of tab_type.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_id
     *
     * @param typeId the value for tab_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_text
     *
     * @return the value of tab_type.type_text
     *
     * @mbggenerated
     */
    public String getTypeText() {
        return typeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_text
     *
     * @param typeText the value for tab_type.type_text
     *
     * @mbggenerated
     */
    public void setTypeText(String typeText) {
        this.typeText = typeText == null ? null : typeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.bak1
     *
     * @return the value of tab_type.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.bak1
     *
     * @param bak1 the value for tab_type.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_type
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TabType other = (TabType) that;
        return (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()))
            && (this.getTypeText() == null ? other.getTypeText() == null : this.getTypeText().equals(other.getTypeText()))
            && (this.getBak1() == null ? other.getBak1() == null : this.getBak1().equals(other.getBak1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_type
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
        result = prime * result + ((getTypeText() == null) ? 0 : getTypeText().hashCode());
        result = prime * result + ((getBak1() == null) ? 0 : getBak1().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeId=").append(typeId);
        sb.append(", typeText=").append(typeText);
        sb.append(", bak1=").append(bak1);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}