package com.sc.dmh.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ViewShouruExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public ViewShouruExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShouruIdIsNull() {
            addCriterion("shouru_id is null");
            return (Criteria) this;
        }

        public Criteria andShouruIdIsNotNull() {
            addCriterion("shouru_id is not null");
            return (Criteria) this;
        }

        public Criteria andShouruIdEqualTo(Integer value) {
            addCriterion("shouru_id =", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdNotEqualTo(Integer value) {
            addCriterion("shouru_id <>", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdGreaterThan(Integer value) {
            addCriterion("shouru_id >", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shouru_id >=", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdLessThan(Integer value) {
            addCriterion("shouru_id <", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdLessThanOrEqualTo(Integer value) {
            addCriterion("shouru_id <=", value, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdIn(List<Integer> values) {
            addCriterion("shouru_id in", values, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdNotIn(List<Integer> values) {
            addCriterion("shouru_id not in", values, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdBetween(Integer value1, Integer value2) {
            addCriterion("shouru_id between", value1, value2, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shouru_id not between", value1, value2, "shouruId");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyIsNull() {
            addCriterion("shouru_money is null");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyIsNotNull() {
            addCriterion("shouru_money is not null");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyEqualTo(BigDecimal value) {
            addCriterion("shouru_money =", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyNotEqualTo(BigDecimal value) {
            addCriterion("shouru_money <>", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyGreaterThan(BigDecimal value) {
            addCriterion("shouru_money >", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shouru_money >=", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyLessThan(BigDecimal value) {
            addCriterion("shouru_money <", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shouru_money <=", value, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyIn(List<BigDecimal> values) {
            addCriterion("shouru_money in", values, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyNotIn(List<BigDecimal> values) {
            addCriterion("shouru_money not in", values, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shouru_money between", value1, value2, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shouru_money not between", value1, value2, "shouruMoney");
            return (Criteria) this;
        }

        public Criteria andShouruDateIsNull() {
            addCriterion("shouru_date is null");
            return (Criteria) this;
        }

        public Criteria andShouruDateIsNotNull() {
            addCriterion("shouru_date is not null");
            return (Criteria) this;
        }

        public Criteria andShouruDateEqualTo(Date value) {
            addCriterion("shouru_date =", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateNotEqualTo(Date value) {
            addCriterion("shouru_date <>", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateGreaterThan(Date value) {
            addCriterion("shouru_date >", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateGreaterThanOrEqualTo(Date value) {
            addCriterion("shouru_date >=", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateLessThan(Date value) {
            addCriterion("shouru_date <", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateLessThanOrEqualTo(Date value) {
            addCriterion("shouru_date <=", value, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateIn(List<Date> values) {
            addCriterion("shouru_date in", values, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateNotIn(List<Date> values) {
            addCriterion("shouru_date not in", values, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateBetween(Date value1, Date value2) {
            addCriterion("shouru_date between", value1, value2, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruDateNotBetween(Date value1, Date value2) {
            addCriterion("shouru_date not between", value1, value2, "shouruDate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateIsNull() {
            addCriterion("shouru_autodate is null");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateIsNotNull() {
            addCriterion("shouru_autodate is not null");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateEqualTo(Date value) {
            addCriterion("shouru_autodate =", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateNotEqualTo(Date value) {
            addCriterion("shouru_autodate <>", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateGreaterThan(Date value) {
            addCriterion("shouru_autodate >", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateGreaterThanOrEqualTo(Date value) {
            addCriterion("shouru_autodate >=", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateLessThan(Date value) {
            addCriterion("shouru_autodate <", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateLessThanOrEqualTo(Date value) {
            addCriterion("shouru_autodate <=", value, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateIn(List<Date> values) {
            addCriterion("shouru_autodate in", values, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateNotIn(List<Date> values) {
            addCriterion("shouru_autodate not in", values, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateBetween(Date value1, Date value2) {
            addCriterion("shouru_autodate between", value1, value2, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruAutodateNotBetween(Date value1, Date value2) {
            addCriterion("shouru_autodate not between", value1, value2, "shouruAutodate");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuIsNull() {
            addCriterion("shouru_beizu is null");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuIsNotNull() {
            addCriterion("shouru_beizu is not null");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuEqualTo(String value) {
            addCriterion("shouru_beizu =", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuNotEqualTo(String value) {
            addCriterion("shouru_beizu <>", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuGreaterThan(String value) {
            addCriterion("shouru_beizu >", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuGreaterThanOrEqualTo(String value) {
            addCriterion("shouru_beizu >=", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuLessThan(String value) {
            addCriterion("shouru_beizu <", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuLessThanOrEqualTo(String value) {
            addCriterion("shouru_beizu <=", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuLike(String value) {
            addCriterion("shouru_beizu like", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuNotLike(String value) {
            addCriterion("shouru_beizu not like", value, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuIn(List<String> values) {
            addCriterion("shouru_beizu in", values, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuNotIn(List<String> values) {
            addCriterion("shouru_beizu not in", values, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuBetween(String value1, String value2) {
            addCriterion("shouru_beizu between", value1, value2, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andShouruBeizuNotBetween(String value1, String value2) {
            addCriterion("shouru_beizu not between", value1, value2, "shouruBeizu");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDepIdIsNull() {
            addCriterion("dep_id is null");
            return (Criteria) this;
        }

        public Criteria andDepIdIsNotNull() {
            addCriterion("dep_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepIdEqualTo(Integer value) {
            addCriterion("dep_id =", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotEqualTo(Integer value) {
            addCriterion("dep_id <>", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdGreaterThan(Integer value) {
            addCriterion("dep_id >", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dep_id >=", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdLessThan(Integer value) {
            addCriterion("dep_id <", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdLessThanOrEqualTo(Integer value) {
            addCriterion("dep_id <=", value, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdIn(List<Integer> values) {
            addCriterion("dep_id in", values, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotIn(List<Integer> values) {
            addCriterion("dep_id not in", values, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdBetween(Integer value1, Integer value2) {
            addCriterion("dep_id between", value1, value2, "depId");
            return (Criteria) this;
        }

        public Criteria andDepIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dep_id not between", value1, value2, "depId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdIsNull() {
            addCriterion("srtype_id is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdIsNotNull() {
            addCriterion("srtype_id is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdEqualTo(Integer value) {
            addCriterion("srtype_id =", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotEqualTo(Integer value) {
            addCriterion("srtype_id <>", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdGreaterThan(Integer value) {
            addCriterion("srtype_id >", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("srtype_id >=", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdLessThan(Integer value) {
            addCriterion("srtype_id <", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("srtype_id <=", value, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdIn(List<Integer> values) {
            addCriterion("srtype_id in", values, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotIn(List<Integer> values) {
            addCriterion("srtype_id not in", values, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdBetween(Integer value1, Integer value2) {
            addCriterion("srtype_id between", value1, value2, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("srtype_id not between", value1, value2, "srtypeId");
            return (Criteria) this;
        }

        public Criteria andSrtypeIsNull() {
            addCriterion("srtype is null");
            return (Criteria) this;
        }

        public Criteria andSrtypeIsNotNull() {
            addCriterion("srtype is not null");
            return (Criteria) this;
        }

        public Criteria andSrtypeEqualTo(String value) {
            addCriterion("srtype =", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotEqualTo(String value) {
            addCriterion("srtype <>", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeGreaterThan(String value) {
            addCriterion("srtype >", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeGreaterThanOrEqualTo(String value) {
            addCriterion("srtype >=", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLessThan(String value) {
            addCriterion("srtype <", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLessThanOrEqualTo(String value) {
            addCriterion("srtype <=", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeLike(String value) {
            addCriterion("srtype like", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotLike(String value) {
            addCriterion("srtype not like", value, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeIn(List<String> values) {
            addCriterion("srtype in", values, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotIn(List<String> values) {
            addCriterion("srtype not in", values, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeBetween(String value1, String value2) {
            addCriterion("srtype between", value1, value2, "srtype");
            return (Criteria) this;
        }

        public Criteria andSrtypeNotBetween(String value1, String value2) {
            addCriterion("srtype not between", value1, value2, "srtype");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNull() {
            addCriterion("department_name is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNotNull() {
            addCriterion("department_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameEqualTo(String value) {
            addCriterion("department_name =", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotEqualTo(String value) {
            addCriterion("department_name <>", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThan(String value) {
            addCriterion("department_name >", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("department_name >=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThan(String value) {
            addCriterion("department_name <", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("department_name <=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLike(String value) {
            addCriterion("department_name like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotLike(String value) {
            addCriterion("department_name not like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIn(List<String> values) {
            addCriterion("department_name in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotIn(List<String> values) {
            addCriterion("department_name not in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameBetween(String value1, String value2) {
            addCriterion("department_name between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotBetween(String value1, String value2) {
            addCriterion("department_name not between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIsNull() {
            addCriterion("department_order is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIsNotNull() {
            addCriterion("department_order is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderEqualTo(Integer value) {
            addCriterion("department_order =", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotEqualTo(Integer value) {
            addCriterion("department_order <>", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderGreaterThan(Integer value) {
            addCriterion("department_order >", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_order >=", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderLessThan(Integer value) {
            addCriterion("department_order <", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderLessThanOrEqualTo(Integer value) {
            addCriterion("department_order <=", value, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderIn(List<Integer> values) {
            addCriterion("department_order in", values, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotIn(List<Integer> values) {
            addCriterion("department_order not in", values, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderBetween(Integer value1, Integer value2) {
            addCriterion("department_order between", value1, value2, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andDepartmentOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("department_order not between", value1, value2, "departmentOrder");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNull() {
            addCriterion("user_xm is null");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNotNull() {
            addCriterion("user_xm is not null");
            return (Criteria) this;
        }

        public Criteria andUserXmEqualTo(String value) {
            addCriterion("user_xm =", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotEqualTo(String value) {
            addCriterion("user_xm <>", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThan(String value) {
            addCriterion("user_xm >", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThanOrEqualTo(String value) {
            addCriterion("user_xm >=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThan(String value) {
            addCriterion("user_xm <", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThanOrEqualTo(String value) {
            addCriterion("user_xm <=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLike(String value) {
            addCriterion("user_xm like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotLike(String value) {
            addCriterion("user_xm not like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmIn(List<String> values) {
            addCriterion("user_xm in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotIn(List<String> values) {
            addCriterion("user_xm not in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmBetween(String value1, String value2) {
            addCriterion("user_xm between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotBetween(String value1, String value2) {
            addCriterion("user_xm not between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNull() {
            addCriterion("sh_number is null");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNotNull() {
            addCriterion("sh_number is not null");
            return (Criteria) this;
        }

        public Criteria andShNumberEqualTo(Integer value) {
            addCriterion("sh_number =", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotEqualTo(Integer value) {
            addCriterion("sh_number <>", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThan(Integer value) {
            addCriterion("sh_number >", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("sh_number >=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThan(Integer value) {
            addCriterion("sh_number <", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThanOrEqualTo(Integer value) {
            addCriterion("sh_number <=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberIn(List<Integer> values) {
            addCriterion("sh_number in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotIn(List<Integer> values) {
            addCriterion("sh_number not in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberBetween(Integer value1, Integer value2) {
            addCriterion("sh_number between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("sh_number not between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andUseZwIsNull() {
            addCriterion("use_zw is null");
            return (Criteria) this;
        }

        public Criteria andUseZwIsNotNull() {
            addCriterion("use_zw is not null");
            return (Criteria) this;
        }

        public Criteria andUseZwEqualTo(String value) {
            addCriterion("use_zw =", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotEqualTo(String value) {
            addCriterion("use_zw <>", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwGreaterThan(String value) {
            addCriterion("use_zw >", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwGreaterThanOrEqualTo(String value) {
            addCriterion("use_zw >=", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLessThan(String value) {
            addCriterion("use_zw <", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLessThanOrEqualTo(String value) {
            addCriterion("use_zw <=", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLike(String value) {
            addCriterion("use_zw like", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotLike(String value) {
            addCriterion("use_zw not like", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwIn(List<String> values) {
            addCriterion("use_zw in", values, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotIn(List<String> values) {
            addCriterion("use_zw not in", values, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwBetween(String value1, String value2) {
            addCriterion("use_zw between", value1, value2, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotBetween(String value1, String value2) {
            addCriterion("use_zw not between", value1, value2, "useZw");
            return (Criteria) this;
        }

        public Criteria andShouruStateIsNull() {
            addCriterion("shouru_state is null");
            return (Criteria) this;
        }

        public Criteria andShouruStateIsNotNull() {
            addCriterion("shouru_state is not null");
            return (Criteria) this;
        }

        public Criteria andShouruStateEqualTo(Integer value) {
            addCriterion("shouru_state =", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateNotEqualTo(Integer value) {
            addCriterion("shouru_state <>", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateGreaterThan(Integer value) {
            addCriterion("shouru_state >", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("shouru_state >=", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateLessThan(Integer value) {
            addCriterion("shouru_state <", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateLessThanOrEqualTo(Integer value) {
            addCriterion("shouru_state <=", value, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateIn(List<Integer> values) {
            addCriterion("shouru_state in", values, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateNotIn(List<Integer> values) {
            addCriterion("shouru_state not in", values, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateBetween(Integer value1, Integer value2) {
            addCriterion("shouru_state between", value1, value2, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruStateNotBetween(Integer value1, Integer value2) {
            addCriterion("shouru_state not between", value1, value2, "shouruState");
            return (Criteria) this;
        }

        public Criteria andShouruBak1IsNull() {
            addCriterion("shouru_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andShouruBak1IsNotNull() {
            addCriterion("shouru_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andShouruBak1EqualTo(String value) {
            addCriterion("shouru_bak1 =", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1NotEqualTo(String value) {
            addCriterion("shouru_bak1 <>", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1GreaterThan(String value) {
            addCriterion("shouru_bak1 >", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1GreaterThanOrEqualTo(String value) {
            addCriterion("shouru_bak1 >=", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1LessThan(String value) {
            addCriterion("shouru_bak1 <", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1LessThanOrEqualTo(String value) {
            addCriterion("shouru_bak1 <=", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1Like(String value) {
            addCriterion("shouru_bak1 like", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1NotLike(String value) {
            addCriterion("shouru_bak1 not like", value, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1In(List<String> values) {
            addCriterion("shouru_bak1 in", values, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1NotIn(List<String> values) {
            addCriterion("shouru_bak1 not in", values, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1Between(String value1, String value2) {
            addCriterion("shouru_bak1 between", value1, value2, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak1NotBetween(String value1, String value2) {
            addCriterion("shouru_bak1 not between", value1, value2, "shouruBak1");
            return (Criteria) this;
        }

        public Criteria andShouruBak2IsNull() {
            addCriterion("shouru_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andShouruBak2IsNotNull() {
            addCriterion("shouru_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andShouruBak2EqualTo(String value) {
            addCriterion("shouru_bak2 =", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2NotEqualTo(String value) {
            addCriterion("shouru_bak2 <>", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2GreaterThan(String value) {
            addCriterion("shouru_bak2 >", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2GreaterThanOrEqualTo(String value) {
            addCriterion("shouru_bak2 >=", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2LessThan(String value) {
            addCriterion("shouru_bak2 <", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2LessThanOrEqualTo(String value) {
            addCriterion("shouru_bak2 <=", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2Like(String value) {
            addCriterion("shouru_bak2 like", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2NotLike(String value) {
            addCriterion("shouru_bak2 not like", value, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2In(List<String> values) {
            addCriterion("shouru_bak2 in", values, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2NotIn(List<String> values) {
            addCriterion("shouru_bak2 not in", values, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2Between(String value1, String value2) {
            addCriterion("shouru_bak2 between", value1, value2, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak2NotBetween(String value1, String value2) {
            addCriterion("shouru_bak2 not between", value1, value2, "shouruBak2");
            return (Criteria) this;
        }

        public Criteria andShouruBak3IsNull() {
            addCriterion("shouru_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andShouruBak3IsNotNull() {
            addCriterion("shouru_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andShouruBak3EqualTo(String value) {
            addCriterion("shouru_bak3 =", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3NotEqualTo(String value) {
            addCriterion("shouru_bak3 <>", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3GreaterThan(String value) {
            addCriterion("shouru_bak3 >", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3GreaterThanOrEqualTo(String value) {
            addCriterion("shouru_bak3 >=", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3LessThan(String value) {
            addCriterion("shouru_bak3 <", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3LessThanOrEqualTo(String value) {
            addCriterion("shouru_bak3 <=", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3Like(String value) {
            addCriterion("shouru_bak3 like", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3NotLike(String value) {
            addCriterion("shouru_bak3 not like", value, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3In(List<String> values) {
            addCriterion("shouru_bak3 in", values, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3NotIn(List<String> values) {
            addCriterion("shouru_bak3 not in", values, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3Between(String value1, String value2) {
            addCriterion("shouru_bak3 between", value1, value2, "shouruBak3");
            return (Criteria) this;
        }

        public Criteria andShouruBak3NotBetween(String value1, String value2) {
            addCriterion("shouru_bak3 not between", value1, value2, "shouruBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_shouru
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_shouru
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}