package com.sc.dmh.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ViewCgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public ViewCgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCgIdIsNull() {
            addCriterion("cg_id is null");
            return (Criteria) this;
        }

        public Criteria andCgIdIsNotNull() {
            addCriterion("cg_id is not null");
            return (Criteria) this;
        }

        public Criteria andCgIdEqualTo(Integer value) {
            addCriterion("cg_id =", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotEqualTo(Integer value) {
            addCriterion("cg_id <>", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdGreaterThan(Integer value) {
            addCriterion("cg_id >", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_id >=", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdLessThan(Integer value) {
            addCriterion("cg_id <", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdLessThanOrEqualTo(Integer value) {
            addCriterion("cg_id <=", value, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdIn(List<Integer> values) {
            addCriterion("cg_id in", values, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotIn(List<Integer> values) {
            addCriterion("cg_id not in", values, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdBetween(Integer value1, Integer value2) {
            addCriterion("cg_id between", value1, value2, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_id not between", value1, value2, "cgId");
            return (Criteria) this;
        }

        public Criteria andCgSlIsNull() {
            addCriterion("cg_sl is null");
            return (Criteria) this;
        }

        public Criteria andCgSlIsNotNull() {
            addCriterion("cg_sl is not null");
            return (Criteria) this;
        }

        public Criteria andCgSlEqualTo(BigDecimal value) {
            addCriterion("cg_sl =", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlNotEqualTo(BigDecimal value) {
            addCriterion("cg_sl <>", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlGreaterThan(BigDecimal value) {
            addCriterion("cg_sl >", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cg_sl >=", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlLessThan(BigDecimal value) {
            addCriterion("cg_sl <", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cg_sl <=", value, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlIn(List<BigDecimal> values) {
            addCriterion("cg_sl in", values, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlNotIn(List<BigDecimal> values) {
            addCriterion("cg_sl not in", values, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cg_sl between", value1, value2, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cg_sl not between", value1, value2, "cgSl");
            return (Criteria) this;
        }

        public Criteria andCgMoneyIsNull() {
            addCriterion("cg_money is null");
            return (Criteria) this;
        }

        public Criteria andCgMoneyIsNotNull() {
            addCriterion("cg_money is not null");
            return (Criteria) this;
        }

        public Criteria andCgMoneyEqualTo(BigDecimal value) {
            addCriterion("cg_money =", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyNotEqualTo(BigDecimal value) {
            addCriterion("cg_money <>", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyGreaterThan(BigDecimal value) {
            addCriterion("cg_money >", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cg_money >=", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyLessThan(BigDecimal value) {
            addCriterion("cg_money <", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cg_money <=", value, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyIn(List<BigDecimal> values) {
            addCriterion("cg_money in", values, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyNotIn(List<BigDecimal> values) {
            addCriterion("cg_money not in", values, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cg_money between", value1, value2, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cg_money not between", value1, value2, "cgMoney");
            return (Criteria) this;
        }

        public Criteria andCgSjIsNull() {
            addCriterion("cg_sj is null");
            return (Criteria) this;
        }

        public Criteria andCgSjIsNotNull() {
            addCriterion("cg_sj is not null");
            return (Criteria) this;
        }

        public Criteria andCgSjEqualTo(Integer value) {
            addCriterion("cg_sj =", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjNotEqualTo(Integer value) {
            addCriterion("cg_sj <>", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjGreaterThan(Integer value) {
            addCriterion("cg_sj >", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_sj >=", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjLessThan(Integer value) {
            addCriterion("cg_sj <", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjLessThanOrEqualTo(Integer value) {
            addCriterion("cg_sj <=", value, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjIn(List<Integer> values) {
            addCriterion("cg_sj in", values, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjNotIn(List<Integer> values) {
            addCriterion("cg_sj not in", values, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjBetween(Integer value1, Integer value2) {
            addCriterion("cg_sj between", value1, value2, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgSjNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_sj not between", value1, value2, "cgSj");
            return (Criteria) this;
        }

        public Criteria andCgBxIsNull() {
            addCriterion("cg_bx is null");
            return (Criteria) this;
        }

        public Criteria andCgBxIsNotNull() {
            addCriterion("cg_bx is not null");
            return (Criteria) this;
        }

        public Criteria andCgBxEqualTo(Integer value) {
            addCriterion("cg_bx =", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxNotEqualTo(Integer value) {
            addCriterion("cg_bx <>", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxGreaterThan(Integer value) {
            addCriterion("cg_bx >", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_bx >=", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxLessThan(Integer value) {
            addCriterion("cg_bx <", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxLessThanOrEqualTo(Integer value) {
            addCriterion("cg_bx <=", value, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxIn(List<Integer> values) {
            addCriterion("cg_bx in", values, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxNotIn(List<Integer> values) {
            addCriterion("cg_bx not in", values, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxBetween(Integer value1, Integer value2) {
            addCriterion("cg_bx between", value1, value2, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgBxNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_bx not between", value1, value2, "cgBx");
            return (Criteria) this;
        }

        public Criteria andCgDateIsNull() {
            addCriterion("cg_date is null");
            return (Criteria) this;
        }

        public Criteria andCgDateIsNotNull() {
            addCriterion("cg_date is not null");
            return (Criteria) this;
        }

        public Criteria andCgDateEqualTo(Date value) {
            addCriterion("cg_date =", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateNotEqualTo(Date value) {
            addCriterion("cg_date <>", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateGreaterThan(Date value) {
            addCriterion("cg_date >", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cg_date >=", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateLessThan(Date value) {
            addCriterion("cg_date <", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateLessThanOrEqualTo(Date value) {
            addCriterion("cg_date <=", value, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateIn(List<Date> values) {
            addCriterion("cg_date in", values, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateNotIn(List<Date> values) {
            addCriterion("cg_date not in", values, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateBetween(Date value1, Date value2) {
            addCriterion("cg_date between", value1, value2, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgDateNotBetween(Date value1, Date value2) {
            addCriterion("cg_date not between", value1, value2, "cgDate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateIsNull() {
            addCriterion("cg_autodate is null");
            return (Criteria) this;
        }

        public Criteria andCgAutodateIsNotNull() {
            addCriterion("cg_autodate is not null");
            return (Criteria) this;
        }

        public Criteria andCgAutodateEqualTo(Date value) {
            addCriterion("cg_autodate =", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateNotEqualTo(Date value) {
            addCriterion("cg_autodate <>", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateGreaterThan(Date value) {
            addCriterion("cg_autodate >", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateGreaterThanOrEqualTo(Date value) {
            addCriterion("cg_autodate >=", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateLessThan(Date value) {
            addCriterion("cg_autodate <", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateLessThanOrEqualTo(Date value) {
            addCriterion("cg_autodate <=", value, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateIn(List<Date> values) {
            addCriterion("cg_autodate in", values, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateNotIn(List<Date> values) {
            addCriterion("cg_autodate not in", values, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateBetween(Date value1, Date value2) {
            addCriterion("cg_autodate between", value1, value2, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgAutodateNotBetween(Date value1, Date value2) {
            addCriterion("cg_autodate not between", value1, value2, "cgAutodate");
            return (Criteria) this;
        }

        public Criteria andCgBak1IsNull() {
            addCriterion("cg_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andCgBak1IsNotNull() {
            addCriterion("cg_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andCgBak1EqualTo(String value) {
            addCriterion("cg_bak1 =", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1NotEqualTo(String value) {
            addCriterion("cg_bak1 <>", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1GreaterThan(String value) {
            addCriterion("cg_bak1 >", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1GreaterThanOrEqualTo(String value) {
            addCriterion("cg_bak1 >=", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1LessThan(String value) {
            addCriterion("cg_bak1 <", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1LessThanOrEqualTo(String value) {
            addCriterion("cg_bak1 <=", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1Like(String value) {
            addCriterion("cg_bak1 like", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1NotLike(String value) {
            addCriterion("cg_bak1 not like", value, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1In(List<String> values) {
            addCriterion("cg_bak1 in", values, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1NotIn(List<String> values) {
            addCriterion("cg_bak1 not in", values, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1Between(String value1, String value2) {
            addCriterion("cg_bak1 between", value1, value2, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak1NotBetween(String value1, String value2) {
            addCriterion("cg_bak1 not between", value1, value2, "cgBak1");
            return (Criteria) this;
        }

        public Criteria andCgBak2IsNull() {
            addCriterion("cg_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andCgBak2IsNotNull() {
            addCriterion("cg_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andCgBak2EqualTo(String value) {
            addCriterion("cg_bak2 =", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2NotEqualTo(String value) {
            addCriterion("cg_bak2 <>", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2GreaterThan(String value) {
            addCriterion("cg_bak2 >", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2GreaterThanOrEqualTo(String value) {
            addCriterion("cg_bak2 >=", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2LessThan(String value) {
            addCriterion("cg_bak2 <", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2LessThanOrEqualTo(String value) {
            addCriterion("cg_bak2 <=", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2Like(String value) {
            addCriterion("cg_bak2 like", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2NotLike(String value) {
            addCriterion("cg_bak2 not like", value, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2In(List<String> values) {
            addCriterion("cg_bak2 in", values, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2NotIn(List<String> values) {
            addCriterion("cg_bak2 not in", values, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2Between(String value1, String value2) {
            addCriterion("cg_bak2 between", value1, value2, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak2NotBetween(String value1, String value2) {
            addCriterion("cg_bak2 not between", value1, value2, "cgBak2");
            return (Criteria) this;
        }

        public Criteria andCgBak3IsNull() {
            addCriterion("cg_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andCgBak3IsNotNull() {
            addCriterion("cg_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andCgBak3EqualTo(String value) {
            addCriterion("cg_bak3 =", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3NotEqualTo(String value) {
            addCriterion("cg_bak3 <>", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3GreaterThan(String value) {
            addCriterion("cg_bak3 >", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3GreaterThanOrEqualTo(String value) {
            addCriterion("cg_bak3 >=", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3LessThan(String value) {
            addCriterion("cg_bak3 <", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3LessThanOrEqualTo(String value) {
            addCriterion("cg_bak3 <=", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3Like(String value) {
            addCriterion("cg_bak3 like", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3NotLike(String value) {
            addCriterion("cg_bak3 not like", value, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3In(List<String> values) {
            addCriterion("cg_bak3 in", values, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3NotIn(List<String> values) {
            addCriterion("cg_bak3 not in", values, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3Between(String value1, String value2) {
            addCriterion("cg_bak3 between", value1, value2, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andCgBak3NotBetween(String value1, String value2) {
            addCriterion("cg_bak3 not between", value1, value2, "cgBak3");
            return (Criteria) this;
        }

        public Criteria andScNameIsNull() {
            addCriterion("sc_name is null");
            return (Criteria) this;
        }

        public Criteria andScNameIsNotNull() {
            addCriterion("sc_name is not null");
            return (Criteria) this;
        }

        public Criteria andScNameEqualTo(String value) {
            addCriterion("sc_name =", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotEqualTo(String value) {
            addCriterion("sc_name <>", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThan(String value) {
            addCriterion("sc_name >", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_name >=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThan(String value) {
            addCriterion("sc_name <", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThanOrEqualTo(String value) {
            addCriterion("sc_name <=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLike(String value) {
            addCriterion("sc_name like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotLike(String value) {
            addCriterion("sc_name not like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameIn(List<String> values) {
            addCriterion("sc_name in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotIn(List<String> values) {
            addCriterion("sc_name not in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameBetween(String value1, String value2) {
            addCriterion("sc_name between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotBetween(String value1, String value2) {
            addCriterion("sc_name not between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andShNameIsNull() {
            addCriterion("sh_name is null");
            return (Criteria) this;
        }

        public Criteria andShNameIsNotNull() {
            addCriterion("sh_name is not null");
            return (Criteria) this;
        }

        public Criteria andShNameEqualTo(String value) {
            addCriterion("sh_name =", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotEqualTo(String value) {
            addCriterion("sh_name <>", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameGreaterThan(String value) {
            addCriterion("sh_name >", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameGreaterThanOrEqualTo(String value) {
            addCriterion("sh_name >=", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLessThan(String value) {
            addCriterion("sh_name <", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLessThanOrEqualTo(String value) {
            addCriterion("sh_name <=", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLike(String value) {
            addCriterion("sh_name like", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotLike(String value) {
            addCriterion("sh_name not like", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameIn(List<String> values) {
            addCriterion("sh_name in", values, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotIn(List<String> values) {
            addCriterion("sh_name not in", values, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameBetween(String value1, String value2) {
            addCriterion("sh_name between", value1, value2, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotBetween(String value1, String value2) {
            addCriterion("sh_name not between", value1, value2, "shName");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNull() {
            addCriterion("user_xm is null");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNotNull() {
            addCriterion("user_xm is not null");
            return (Criteria) this;
        }

        public Criteria andUserXmEqualTo(String value) {
            addCriterion("user_xm =", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotEqualTo(String value) {
            addCriterion("user_xm <>", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThan(String value) {
            addCriterion("user_xm >", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThanOrEqualTo(String value) {
            addCriterion("user_xm >=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThan(String value) {
            addCriterion("user_xm <", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThanOrEqualTo(String value) {
            addCriterion("user_xm <=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLike(String value) {
            addCriterion("user_xm like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotLike(String value) {
            addCriterion("user_xm not like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmIn(List<String> values) {
            addCriterion("user_xm in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotIn(List<String> values) {
            addCriterion("user_xm not in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmBetween(String value1, String value2) {
            addCriterion("user_xm between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotBetween(String value1, String value2) {
            addCriterion("user_xm not between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNull() {
            addCriterion("department_name is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNotNull() {
            addCriterion("department_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameEqualTo(String value) {
            addCriterion("department_name =", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotEqualTo(String value) {
            addCriterion("department_name <>", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThan(String value) {
            addCriterion("department_name >", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("department_name >=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThan(String value) {
            addCriterion("department_name <", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("department_name <=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLike(String value) {
            addCriterion("department_name like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotLike(String value) {
            addCriterion("department_name not like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIn(List<String> values) {
            addCriterion("department_name in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotIn(List<String> values) {
            addCriterion("department_name not in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameBetween(String value1, String value2) {
            addCriterion("department_name between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotBetween(String value1, String value2) {
            addCriterion("department_name not between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andCgShidIsNull() {
            addCriterion("cg_shid is null");
            return (Criteria) this;
        }

        public Criteria andCgShidIsNotNull() {
            addCriterion("cg_shid is not null");
            return (Criteria) this;
        }

        public Criteria andCgShidEqualTo(Integer value) {
            addCriterion("cg_shid =", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidNotEqualTo(Integer value) {
            addCriterion("cg_shid <>", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidGreaterThan(Integer value) {
            addCriterion("cg_shid >", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_shid >=", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidLessThan(Integer value) {
            addCriterion("cg_shid <", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidLessThanOrEqualTo(Integer value) {
            addCriterion("cg_shid <=", value, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidIn(List<Integer> values) {
            addCriterion("cg_shid in", values, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidNotIn(List<Integer> values) {
            addCriterion("cg_shid not in", values, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidBetween(Integer value1, Integer value2) {
            addCriterion("cg_shid between", value1, value2, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgShidNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_shid not between", value1, value2, "cgShid");
            return (Criteria) this;
        }

        public Criteria andCgUseridIsNull() {
            addCriterion("cg_userid is null");
            return (Criteria) this;
        }

        public Criteria andCgUseridIsNotNull() {
            addCriterion("cg_userid is not null");
            return (Criteria) this;
        }

        public Criteria andCgUseridEqualTo(Integer value) {
            addCriterion("cg_userid =", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridNotEqualTo(Integer value) {
            addCriterion("cg_userid <>", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridGreaterThan(Integer value) {
            addCriterion("cg_userid >", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_userid >=", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridLessThan(Integer value) {
            addCriterion("cg_userid <", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridLessThanOrEqualTo(Integer value) {
            addCriterion("cg_userid <=", value, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridIn(List<Integer> values) {
            addCriterion("cg_userid in", values, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridNotIn(List<Integer> values) {
            addCriterion("cg_userid not in", values, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridBetween(Integer value1, Integer value2) {
            addCriterion("cg_userid between", value1, value2, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_userid not between", value1, value2, "cgUserid");
            return (Criteria) this;
        }

        public Criteria andCgDepidIsNull() {
            addCriterion("cg_depid is null");
            return (Criteria) this;
        }

        public Criteria andCgDepidIsNotNull() {
            addCriterion("cg_depid is not null");
            return (Criteria) this;
        }

        public Criteria andCgDepidEqualTo(Integer value) {
            addCriterion("cg_depid =", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidNotEqualTo(Integer value) {
            addCriterion("cg_depid <>", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidGreaterThan(Integer value) {
            addCriterion("cg_depid >", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_depid >=", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidLessThan(Integer value) {
            addCriterion("cg_depid <", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidLessThanOrEqualTo(Integer value) {
            addCriterion("cg_depid <=", value, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidIn(List<Integer> values) {
            addCriterion("cg_depid in", values, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidNotIn(List<Integer> values) {
            addCriterion("cg_depid not in", values, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidBetween(Integer value1, Integer value2) {
            addCriterion("cg_depid between", value1, value2, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgDepidNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_depid not between", value1, value2, "cgDepid");
            return (Criteria) this;
        }

        public Criteria andCgScidIsNull() {
            addCriterion("cg_scid is null");
            return (Criteria) this;
        }

        public Criteria andCgScidIsNotNull() {
            addCriterion("cg_scid is not null");
            return (Criteria) this;
        }

        public Criteria andCgScidEqualTo(Integer value) {
            addCriterion("cg_scid =", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidNotEqualTo(Integer value) {
            addCriterion("cg_scid <>", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidGreaterThan(Integer value) {
            addCriterion("cg_scid >", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cg_scid >=", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidLessThan(Integer value) {
            addCriterion("cg_scid <", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidLessThanOrEqualTo(Integer value) {
            addCriterion("cg_scid <=", value, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidIn(List<Integer> values) {
            addCriterion("cg_scid in", values, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidNotIn(List<Integer> values) {
            addCriterion("cg_scid not in", values, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidBetween(Integer value1, Integer value2) {
            addCriterion("cg_scid between", value1, value2, "cgScid");
            return (Criteria) this;
        }

        public Criteria andCgScidNotBetween(Integer value1, Integer value2) {
            addCriterion("cg_scid not between", value1, value2, "cgScid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_cg
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_cg
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}