package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ViewCbfp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    private Integer cbfpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    private BigDecimal kemuSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    private Date cbfpDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    private String cbfpBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    private String cbfpBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    private String cbfpBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.user_xm
     *
     * @mbggenerated
     */
    private String userXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.use_zw
     *
     * @mbggenerated
     */
    private String useZw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.sh_number
     *
     * @mbggenerated
     */
    private Integer shNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.department_name
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.kemu_name
     *
     * @mbggenerated
     */
    private String kemuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cbfp.kemu_fpxm
     *
     * @mbggenerated
     */
    private String kemuFpxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.cbfp_id
     *
     * @return the value of view_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    public Integer getCbfpId() {
        return cbfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.cbfp_id
     *
     * @param cbfpId the value for view_cbfp.cbfp_id
     *
     * @mbggenerated
     */
    public void setCbfpId(Integer cbfpId) {
        this.cbfpId = cbfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.kemu_sum
     *
     * @return the value of view_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    public BigDecimal getKemuSum() {
        return kemuSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.kemu_sum
     *
     * @param kemuSum the value for view_cbfp.kemu_sum
     *
     * @mbggenerated
     */
    public void setKemuSum(BigDecimal kemuSum) {
        this.kemuSum = kemuSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.cbfp_date
     *
     * @return the value of view_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    public Date getCbfpDate() {
        return cbfpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.cbfp_date
     *
     * @param cbfpDate the value for view_cbfp.cbfp_date
     *
     * @mbggenerated
     */
    public void setCbfpDate(Date cbfpDate) {
        this.cbfpDate = cbfpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.cbfp_bak1
     *
     * @return the value of view_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    public String getCbfpBak1() {
        return cbfpBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.cbfp_bak1
     *
     * @param cbfpBak1 the value for view_cbfp.cbfp_bak1
     *
     * @mbggenerated
     */
    public void setCbfpBak1(String cbfpBak1) {
        this.cbfpBak1 = cbfpBak1 == null ? null : cbfpBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.cbfp_bak2
     *
     * @return the value of view_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    public String getCbfpBak2() {
        return cbfpBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.cbfp_bak2
     *
     * @param cbfpBak2 the value for view_cbfp.cbfp_bak2
     *
     * @mbggenerated
     */
    public void setCbfpBak2(String cbfpBak2) {
        this.cbfpBak2 = cbfpBak2 == null ? null : cbfpBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.cbfp_bak3
     *
     * @return the value of view_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    public String getCbfpBak3() {
        return cbfpBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.cbfp_bak3
     *
     * @param cbfpBak3 the value for view_cbfp.cbfp_bak3
     *
     * @mbggenerated
     */
    public void setCbfpBak3(String cbfpBak3) {
        this.cbfpBak3 = cbfpBak3 == null ? null : cbfpBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.user_xm
     *
     * @return the value of view_cbfp.user_xm
     *
     * @mbggenerated
     */
    public String getUserXm() {
        return userXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.user_xm
     *
     * @param userXm the value for view_cbfp.user_xm
     *
     * @mbggenerated
     */
    public void setUserXm(String userXm) {
        this.userXm = userXm == null ? null : userXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.use_zw
     *
     * @return the value of view_cbfp.use_zw
     *
     * @mbggenerated
     */
    public String getUseZw() {
        return useZw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.use_zw
     *
     * @param useZw the value for view_cbfp.use_zw
     *
     * @mbggenerated
     */
    public void setUseZw(String useZw) {
        this.useZw = useZw == null ? null : useZw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.user_name
     *
     * @return the value of view_cbfp.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.user_name
     *
     * @param userName the value for view_cbfp.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.sh_number
     *
     * @return the value of view_cbfp.sh_number
     *
     * @mbggenerated
     */
    public Integer getShNumber() {
        return shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.sh_number
     *
     * @param shNumber the value for view_cbfp.sh_number
     *
     * @mbggenerated
     */
    public void setShNumber(Integer shNumber) {
        this.shNumber = shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.department_name
     *
     * @return the value of view_cbfp.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.department_name
     *
     * @param departmentName the value for view_cbfp.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.kemu_name
     *
     * @return the value of view_cbfp.kemu_name
     *
     * @mbggenerated
     */
    public String getKemuName() {
        return kemuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.kemu_name
     *
     * @param kemuName the value for view_cbfp.kemu_name
     *
     * @mbggenerated
     */
    public void setKemuName(String kemuName) {
        this.kemuName = kemuName == null ? null : kemuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cbfp.kemu_fpxm
     *
     * @return the value of view_cbfp.kemu_fpxm
     *
     * @mbggenerated
     */
    public String getKemuFpxm() {
        return kemuFpxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_cbfp.kemu_fpxm
     *
     * @param kemuFpxm the value for view_cbfp.kemu_fpxm
     *
     * @mbggenerated
     */
    public void setKemuFpxm(String kemuFpxm) {
        this.kemuFpxm = kemuFpxm == null ? null : kemuFpxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ViewCbfp other = (ViewCbfp) that;
        return (this.getCbfpId() == null ? other.getCbfpId() == null : this.getCbfpId().equals(other.getCbfpId()))
            && (this.getKemuSum() == null ? other.getKemuSum() == null : this.getKemuSum().equals(other.getKemuSum()))
            && (this.getCbfpDate() == null ? other.getCbfpDate() == null : this.getCbfpDate().equals(other.getCbfpDate()))
            && (this.getCbfpBak1() == null ? other.getCbfpBak1() == null : this.getCbfpBak1().equals(other.getCbfpBak1()))
            && (this.getCbfpBak2() == null ? other.getCbfpBak2() == null : this.getCbfpBak2().equals(other.getCbfpBak2()))
            && (this.getCbfpBak3() == null ? other.getCbfpBak3() == null : this.getCbfpBak3().equals(other.getCbfpBak3()))
            && (this.getUserXm() == null ? other.getUserXm() == null : this.getUserXm().equals(other.getUserXm()))
            && (this.getUseZw() == null ? other.getUseZw() == null : this.getUseZw().equals(other.getUseZw()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getShNumber() == null ? other.getShNumber() == null : this.getShNumber().equals(other.getShNumber()))
            && (this.getDepartmentName() == null ? other.getDepartmentName() == null : this.getDepartmentName().equals(other.getDepartmentName()))
            && (this.getKemuName() == null ? other.getKemuName() == null : this.getKemuName().equals(other.getKemuName()))
            && (this.getKemuFpxm() == null ? other.getKemuFpxm() == null : this.getKemuFpxm().equals(other.getKemuFpxm()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCbfpId() == null) ? 0 : getCbfpId().hashCode());
        result = prime * result + ((getKemuSum() == null) ? 0 : getKemuSum().hashCode());
        result = prime * result + ((getCbfpDate() == null) ? 0 : getCbfpDate().hashCode());
        result = prime * result + ((getCbfpBak1() == null) ? 0 : getCbfpBak1().hashCode());
        result = prime * result + ((getCbfpBak2() == null) ? 0 : getCbfpBak2().hashCode());
        result = prime * result + ((getCbfpBak3() == null) ? 0 : getCbfpBak3().hashCode());
        result = prime * result + ((getUserXm() == null) ? 0 : getUserXm().hashCode());
        result = prime * result + ((getUseZw() == null) ? 0 : getUseZw().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getShNumber() == null) ? 0 : getShNumber().hashCode());
        result = prime * result + ((getDepartmentName() == null) ? 0 : getDepartmentName().hashCode());
        result = prime * result + ((getKemuName() == null) ? 0 : getKemuName().hashCode());
        result = prime * result + ((getKemuFpxm() == null) ? 0 : getKemuFpxm().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cbfp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cbfpId=").append(cbfpId);
        sb.append(", kemuSum=").append(kemuSum);
        sb.append(", cbfpDate=").append(cbfpDate);
        sb.append(", cbfpBak1=").append(cbfpBak1);
        sb.append(", cbfpBak2=").append(cbfpBak2);
        sb.append(", cbfpBak3=").append(cbfpBak3);
        sb.append(", userXm=").append(userXm);
        sb.append(", useZw=").append(useZw);
        sb.append(", userName=").append(userName);
        sb.append(", shNumber=").append(shNumber);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", kemuName=").append(kemuName);
        sb.append(", kemuFpxm=").append(kemuFpxm);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}